### ISSUE TITLE
If the director fails to deploy bbl cannot clean up the environment

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh-bootloader#101]
When I was bbl'ing up the vm agent was not responding (separate issue)

```
Waiting for the agent on VM 'vm-18e72ad3-86df-47f0-6d4e-140671c26c39' to be ready...^C
```

I tried to delete everything to redo the up operation

```
mac3057:bbl2 davep$ bbl destroy
Are you sure you want to delete infrastructure for "bbl-env-athabasca-2017-01-30t14-50z"? This operation cannot be undone! (y/N): y
no BOSH director, skipping...


exit status 1
```

bbl didn't delete anything so I tried to do it again
```
mac3057:bbl2 davep$ bbl destroy
The state file has no outputs defined. Define an output
in your configuration with the `output` directive and re-run
`terraform apply` for it to become available.
```

The following now repeats constantly

**Comment by evanfarrar** [comment]
Hello @dprotaso , thanks for your help in identifying this problem.

We've resolved this in bbl v3. We have fixed several situations where we did or didn't save the terraform state after errors inappropriately.
