### ISSUE TITLE
BOSH 260.3 has a director version of '0000'

### ISSUE THREAD

**Issue by benmoss** [cloudfoundry/bosh-bootloader#103]
The release notes for 260.4 mention this: http://bosh.io/releases/github.com/cloudfoundry/bosh?version=260.4

This causes other things to fail, like ODB.

**Comment by evanfarrar** [comment]
OK, thanks for pointing this out. I'll put out a new release with a new stemcell today.

**Comment by evanfarrar** [comment]
Hey @benmoss I'm pretty sure this is fixed by bosh-deployment and bbl v3. Currently the bosh version is 260.5 but if you need a specific version you can supply that with an ops file that patches `/releases/name=bosh/` with the `version`, `sha1` and `url` you need like `bbl up -o boshversion.yml`
