### ISSUE TITLE
provide permalink to latest stable and edge versions or homebrew

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-bootloader#109]
I don't ever want to go to a website to download a new version of a binary.

I would like to use a script of my own that downloads from a permalink ([cf cli permalinks](https://github.com/cloudfoundry/cli#installers-and-compressed-binaries)) or homebrew ([cf cli homebrew instructions](https://github.com/cloudfoundry/cli#installing-using-a-package-manager)).

Thanks!

**Comment by genevievelesperance** [comment]
The next release of bbl will have homebrew instructions in the readme, but you can use the cf tap now: https://github.com/cloudfoundry/bosh-bootloader/tree/develop#install-bosh-bootloader-using-a-package-manager
