### ISSUE TITLE
Create-LB terraform template is incorrect

### ISSUE THREAD

**Issue by robertjsullivan** [cloudfoundry/bosh-bootloader#110]
Got the following error when attempting to create a load balancer:

* google_compute_ssl_certificate.cf-cert: "name": required field is not set
* google_compute_ssl_certificate.cf-cert: : invalid or unknown key: name_prefix

Changing name_prefix to name allows the terraform to run successfully.  This line appears to be identical on develop and master branches.

https://github.com/cloudfoundry/bosh-bootloader/blob/master/commands/gcp_terraform_template.go#L226

**Comment by genevievelesperance** [comment]
We've had the same issue trying to move an environment to gcp with bbl. Is the preferred course of action right now to make changes to bbl to set name_prefix to name ourselves?

**Comment by genevievelesperance** [comment]
@robertjsullivan We updated our terraform from 0.7.7 to 0.8.7 and no longer have this issue.

Re: https://github.com/cloudfoundry/bosh-bootloader/issues/111

**Comment by evanfarrar** [comment]
@robertjsullivan are you still having problems?

**Comment by robertjsullivan** [comment]
We got past it by modifying the template locally.  But I didn't realize the
real culprit was our local install of terraform was behind the version it
needed to be at.  I think it would be good to specify the version of
terraform needed in the README. Looks like 0.8.7 works.

**Comment by evanfarrar** [comment]
Good idea. We have a story to fail fast if 0.8.7 or greater is not available, but I will add it to the readme in the mean time.
