### ISSUE TITLE
bbl create-lbs exit status 1

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry/bosh-bootloader#111]
While trying to use `bbl` on GCP.

When running the following command,

```
$ bbl create-lbs --type cf --key router.key --cert router.crt
```

It outputs error message with no context

```
step: generating terraform template


exit status 1
```

I've got no leads. :-(

**Comment by jaydunk** [comment]
We ran into this issue when we were using 4096 bit RSA key. We reduced it to 2048 and it resolved the problem. It would be nice if bbl returned a more helpful error.

**Comment by dsabeti** [comment]
You can also add `--debug` to your bbl commands to get verbose output -- just be careful, it might leak creds.

**Comment by johnsonj** [comment]
I hit this issue due to an old version of terraform. Upgraded to 0.8.7 and it succeeds.

**Comment by evanfarrar** [comment]
@jtarchie are you still having problems?

**Comment by jtarchie** [comment]
It appears not. Another pair was able to deploy with the certs. Thanks!
