### ISSUE TITLE
Deploying Concourse Guide skips cloud config step

### ISSUE THREAD

**Issue by enocom** [cloudfoundry/bosh-bootloader#113]
I'm following the guide to deploy Concourse on GCP [here](https://github.com/cloudfoundry/bosh-bootloader/blob/master/concourse.md). The guide is clear and helpful. It also omits the step for uploading a cloud config. 

As a bosh user, I'm familiar with the step and understand what needs to be done. A new user, however, would likely struggle without an explicit step in the guide to upload cloud config.

**Comment by evanfarrar** [comment]
Sorry I missed this, but I hope you may have discovered that one of the core features of bosh-bootloader is to upload a cloud config based on your infrastructure. If there is something missing from the cloud config or this didn't happen, I would be concerned and would like to hear about it.

**Comment by enocom** [comment]
@evanfarrar As a bosh user, I was expecting an upload cloud-config step and was initially confused when I didn't have to do that explicitly. When I realized `bbl` had me covered, I was pleasantly surprised and closed this issue.
