### ISSUE TITLE
Feature Request: bbl-state.json should have newlines

### ISSUE THREAD

**Issue by dsabeti** [cloudfoundry/bosh-bootloader#115]
It would be really great if bbl-state.json weren't on a single line. When you try to update and environment, you end up with a massive `git diff`, even if the most of the resources haven't changes.

If the bbl-state.json had newlines (for example, if you just piped it through `jq`), the diffs would come out a lot cleaner, and it would be easier to know what actually changed between runs of `bbl up` (or between your initial `bbl up` and the subsequent `bbl create-lbs`).

**Comment by evanfarrar** [comment]
@dsabeti this is done and is in v3.0.4: https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v3.0.4
