### ISSUE TITLE
Fail test bbl/aws_up_test.go:251

### ISSUE THREAD

**Issue by rauizab** [cloudfoundry/bosh-bootloader#116]
Hi

/usr/local/go/bin/go test -v github.com/cloudfoundry/bosh-bootloader/bbl -run ^TestBbl$

bbl/aws_up_test.go:251: undefined: interpolateArgs

FAIL	github.com/cloudfoundry/bosh-bootloader/bbl [build failed]

**Comment by evanfarrar** [comment]
Hello Raizub,

We use ginkgo to run our tests. You still may have some failing tests that require environment variables for real IaaS credentials to pass, but we're happy to accept patches which pass the other tests and pay for the costs of running the IaaS integration tests in our pipeline.

```
ginkgo -r ./
```
