### ISSUE TITLE
`bbl up` without `--debug` is not very informative

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#120]
It would be helpful if `bbl up` printed a bit more information about what it was currently doing. The complete output from `bbl` terraforming an environment, standing up a director, and updating the cloud config is:

```
bbl up
step: Creating new ssh-keys for the project "cf-capi-ripley"
step: generating cloud config
step: applying cloud config
```

It would be nice to see a bit more info about what it was doing (e.g. "Deploying director, this may take several minutes...") with needing the `--debug` flag.

**Comment by evanfarrar** [comment]
Hey @ljfranklin 

This is a good point, and we've addressed this in two ways in bbl v3.0.4:

1. some missed logging on GCP that we have on AWS
1. overzealous silencing of bosh output. My original intent for `--debug` was just to remove any credentials from being printed by terraform in pipelines by default, and I didn't translate that well enough into stories so it got lost in implementation.
