### ISSUE TITLE
bbl up not idempotent for Google Cloud DNS zone 

### ISSUE THREAD

**Issue by mmb** [cloudfoundry/bosh-bootloader#122]
When `bbl up` creates a zone in Google Cloud DNS it seems to destroy and recreate it from scratch. This gives you new random nameservers in the NS record.

For example the `e1` part will change to `b1`:

```
ns-cloud-e1.googledomains.com.
ns-cloud-e2.googledomains.com.
ns-cloud-e3.googledomains.com.
ns-cloud-e4.googledomains.com.
```

This causes our DNS to stop working because we have an NS record in Route 53 that points to these servers. Is there any way that bbl could not recreate the zone if it already exists?

**Comment by christianang** [comment]
Which `bbl version` are you currently using? This was recently fixed and released in bbl v3.

**Comment by mmb** [comment]
Thanks.

We are using the bbl in cf-deployment-concourse-tasks which is still version 2.1.1.

**Comment by christianang** [comment]
Okay, cool. The team maintaining the cf-deployment-concourse-tasks, release-integration, are currently evaluating bbl v3 and presumably will bump those tasks to use it soon.

I'll close the issue for now, but let us know if you still encounter problems once they bump the bbl version they are using.
