### ISSUE TITLE
bbl up should support {} in state.json

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#123]
We are switching over to using bbl v3 and when we ran `bbl up` with our `bbl-state.json` only having `{}` it gave us the very cryptic error of:

```
Existing bbl environment is incompatible with bbl v3. Create a new environment with v3 to continue.
```

This was resolved by making sure to specific our state file like this:

```
{"version": 3}
```

We'd either like to specify empty json or have a more specific error.

**Comment by zachgersh** [comment]
@evanfarrar can we close this now that it is accepted?

**Comment by evanfarrar** [comment]
It still hasnt been released in a binary, though.

**Comment by evanfarrar** [comment]
This is in v3.1.0
