### ISSUE TITLE
Feature Request: Adding Azure as a supported IaaS

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#126]
I'm sure you've gotten this question before, but I was wondering if there were any short-term or long-term plans to support bbl on Azure.

Our specific use case is spinning up CI environments to test our integration with the Azure SQL Server database.

**Comment by evanfarrar** [comment]
We certainly plan to support Azure, but we are first re-visiting our AWS support to bring it to feature parity with GCP. While implementing the GCP support, we took advantage of Release Integration's terraform template work, integrated with cf-deployment, and smoothed old sore spots (like LB DNS). Not all of that made it back to AWS cloudformation templates.

After we've implemented AWS paving via Terraform, we will have hopefully refactored to the point that any IaaS that terraform supports (like Azure and Openstack) can be added quickly. Azure is next on the list, but this process will realistically take us at least a few weeks to begin.

I'll keep this open for others to voice what they are looking to do with bbl and Azure in this issue, and share our towards Azure support here.

**Comment by jastev** [comment]
Let me know how we can help.  We'd likely be interested in pairing with you on this, if you're open to that.

**Comment by timani** [comment]
+1 to this. The experience on GCP is quite smooth and having the same for Azure would be quite valuable.

**Comment by mxplusb** [comment]
Hey team, this is starting to be a priority for both Pivotal and Microsoft, can you please provide an update to this issue?

**Comment by genevievelesperance** [comment]
@mxplusb This is currently in flight.

**Comment by cforce** [comment]
Great, where can i track it? Can't find any hints in documentation

**Comment by genevievelesperance** [comment]
This is our teams backlog: https://www.pivotaltracker.com/n/projects/1488988
