### ISSUE TITLE
Cloud Formation stack update failed

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#128]
I am deploying to AWS using `bbl 2.0.14`. Due to errors during stack creation (maximum number of VPCs is reached, for example) deployment fails. 

When I fix an error and rerun `bbl up` it can't update stack as it is in `ROLLBACK_COMPLETED` state. 

I would expect `bbl` to recreate this stack instead.

**Comment by evanfarrar** [comment]
@lexsys27 I am not sure if we answered you in slack or anywhere else, sorry for the slow reply here if not. It is unfortunate that the cloudformation stack is not recreated, and you must remove the stack to continue.

However, we've indirectly got a solution to this problem, we're no longer planning on using cloudformation. You can run `bbl up --terraform` to preview this before it becomes the mode of IaaS interaction in BBL v4.

**Comment by lexsys27** [comment]
Good news about moving to the terraform @evanfarrar !

Can you share the date when you plan to release v4? Do you have some kind of public roadmap for it?
