### ISSUE TITLE
Failed to create concourse load balancer on AWS

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#130]
```
$ bbl create-lbs --type concourse

there were 2 errors with 'create-lbs':
    * --cert is required
    * --key is required
```

I have generated certificate and key using following command:

```
openssl req \
       -newkey rsa:2048 -nodes -keyout concourse.eminens.io.key \
       -x509 -days 365 -out concourse.eminens.io.crt
```

```
$ bbl create-lbs --type concourse --cert concourse.eminens.io.crt --key concourse.eminens.io.key

there was 1 error with 'create-lbs':
    * failed to parse private key: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false}  @5

use --debug for additional debug output
```

**Comment by lexsys27** [comment]
This fixes the situations.

```
$ openssl rsa -in key.pem -out rsakey.pem
writing RSA key
$ bbl create-lbs --type concourse --cert concourse.eminens.io.crt --key rsakey.pem
```

Turned out that

> OpenSSL 0.9.8 generates PKCS#1 private keys by default, while OpenSSL 1.0.0 generates PKCS#8 keys. OpenSSL ecparam generates SEC1 EC private keys for ECDSA.

From [here](https://groups.google.com/forum/#!topic/golang-nuts/ZZ1Wt9d268Q)

**Comment by evanfarrar** [comment]
OK, Thanks for reporting, and for getting to the root cause. I will see if we can simply parse that better or at least respond with an error that could lead you towards the proper workaround.

**Comment by rauizab** [comment]
Maybe it is related https://github.com/cloudfoundry/cf-deployment/issues/72
