### ISSUE TITLE
NAT box for Concourse on AWS should allow ICMP traffic

### ISSUE THREAD

**Issue by aashah** [cloudfoundry/bosh-bootloader#139]
Recently our concourse has intermittently encountered bursts of failing jobs/resource check when cloning git repos. At some points, we'd see dozens of resources going orange or full sets of jobs going red with this error:

```
Identity added: /tmp/git-resource-private-key (/tmp/git-resource-private-key)
Cloning into '/tmp/build/get'...
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

When debugging this with the Concourse team, we narrowed this down to our NAT boxes' security group not allowing inbound ICMP traffic. This is necessary when negotiating MTU sizes, which happen over ICMP and packet fragmentation hangs/fails.

Alongside updating the security group, upgrading the NAT instance used can also alleviate this.

- Aakash & @tcdowney, CAPI

**Comment by evanfarrar** [comment]
This change has occurred as of bbl v3.2.0
