### ISSUE TITLE
no such file error when bbl up or bbl destroy

### ISSUE THREAD

**Issue by CraigRubendall** [cloudfoundry/bosh-bootloader#140]
I've tried to follow the instructions listed to use bbl (https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-aws.md).   I'm running 3.1.0:

./bbl version
bbl 3.1.0 (linux/amd64)

Unfortunately, when I run bbl up (and subsequently bbl destroy), I end up at this error message:

<snipped>

Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Finished (00:01:23)
  Compiling package 'bosh_aws_cpi/c2563067cbc20e3406ea36ca2984df2f0eaebcb0'... Finished (00:00:43)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Failed (00:00:01)
Failed installing CPI (00:02:09)

Installing CPI:
  Rendering and uploading Jobs:
    Rendering job templates for installation:
      Rendering templates for job 'aws_cpi/2a34fab07ff9a36e43ede22e227c02918a5ccdef':
        Rendering template src: cpi.json.erb, dst: config/cpi.json:
          Rendering template src: /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/bosh-release-job152537178/templates/cpi.json.erb, dst: /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/rendered-jobs573546306/config/cpi.json:
            Running ruby to render templates:
              Running command: 'ruby /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/erb-renderer351845817/erb-render.rb /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/erb-renderer351845817/erb-context.json /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/bosh-release-job152537178/templates/cpi.json.erb /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/rendered-jobs573546306/config/cpi.json', stdout: '', stderr: '/usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- json (LoadError)
     from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
     from /home/sas/.bosh/installations/e32b7468-bb1c-4654-4b60-13b040c30076/tmp/erb-renderer351845817/erb-render.rb:5
':
                exit status 1

Exit code 1

Ideas?   Note that it's also interesting that once this happens on "up", I also can't destroy all the aws resources it created (thankfully, I can delete the cloudformation stack and, at least most, get cleaned up).

**Comment by genevievelesperance** [comment]
Can you try updating ruby to >1.9?

**Comment by CraigRubendall** [comment]
I upgraded to ruby 2.4.1 and the bbl up command worked successfully.

**Comment by genevievelesperance** [comment]
Great! Closing this issue.
