### ISSUE TITLE
bosh ssh fails with permission denied error

### ISSUE THREAD

**Issue by virajago** [cloudfoundry/bosh-bootloader#144]
Using environment 'https://35.185.104.70:25555' as client 'admin'

Using deployment 'cf'

Task 69. Done
Warning: Permanently added '35.185.104.70' (ECDSA) to the list of known hosts.
Unauthorized use is strictly prohibited. All access and activity
is subject to logging and monitoring.
Permission denied (publickey).
ssh_exchange_identification: Connection closed by remote host

Running SSH:
  1 error(s) occurred:

* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/vijay/.bosh/tmp/ssh-priv-key742580596 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/vijay/.bosh/tmp/ssh-known-hosts637312579 -o ProxyCommand=ssh -tt -W %!h(MISSING):%!p(MISSING) -l vcap 35.185.104.70 -o ServerAliveInterval=30 -o ForwardAgent=no -o ClearAllForwardings=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null 10.0.16.12 -l bosh_f0ea86c5376242a3', stdout: '', stderr: '': exit status 255

Exit code 1

**Comment by genevievelesperance** [comment]
Did you run `chmod 600` on your ssh key?

**Comment by evanfarrar** [comment]
I typically run the following to use BOSH ssh:
```
eval "$(bbl print-env)"
bbl ssh-key > /tmp/ssh-key
chmod 0700 /tmp/ssh-key
ssh-add -D
ssh-add -t 30000 /tmp/ssh-key
```

One interesting thing to note, I run `ssh-add -D` because our linux VMs count public key authentication as a login attempt, and there is a limit to the number of login attempts.

**Comment by genevievelesperance** [comment]
@virajago Please let us know if the above works for you.

**Comment by virajago** [comment]
@evanfarrar @genevievelesperance - thanks, it works.

**Comment by jcfigueiredo** [comment]
Anyone knows if there's a solution for this? I tried the above and it didn't work for me.

**Comment by genevievelesperance** [comment]
@jcfigueiredo have you tried https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/howto-ssh.md ?

What aversion of bbl are you using?

**Comment by jcfigueiredo** [comment]
bbl 3.2.3 (darwin/amd64)

**Comment by jcfigueiredo** [comment]
I realized that based (based on your question) that an older version of bbl takes precedence on my path. I'll destroy my infrastructure and recreate with the new version. Thanks!

**Comment by evanfarrar** [comment]
Closing, but feel free to reopen if you experience a problem even on a newer version.

**Comment by kartiklunkad26** [comment]
Hey! I'm getting this on my machine. I did run the instructions that Evan mentioned above, about clearing my ssh keyring. But it didn't work! 
```
Error: Couldn't resolve host "127.0.0.1:64354"
ssh_exchange_identification: Connection closed by remote host

Running SSH:
  1 error(s) occurred:

* Running command: 'ssh -tt -o ServerAliveInterval=30 -o ForwardAgent=no -o PasswordAuthentication=no -o IdentitiesOnly=yes -o IdentityFile=/Users/kartiklunkad/.bosh/tmp/ssh-priv-key113177059 -o StrictHostKeyChecking=yes -o UserKnownHostsFile=/Users/kartiklunkad/.bosh/tmp/ssh-known-hosts036999654 -o ProxyCommand=nc -x 127.0.0.1:64354 %!h(MISSING) %!p(MISSING) 10.0.16.21 -l bosh_13075cbc99f3458', stdout: '', stderr: '': exit status 255
```
