### ISSUE TITLE
homebrew tap is out of date

### ISSUE THREAD

**Issue by shalako** [cloudfoundry/bosh-bootloader#150]
```
±  | ✓| → brew upgrade cloudfoundry/tap/bbl
Error: cloudfoundry/tap/bbl v3.1.0 already installed
```

Latest release on releases page is v3.2.3.
Please don't make me manually download/install :)

**Comment by evanfarrar** [comment]
Sorry Shannon, we have ask'ed for access to the homebrew repo, and I may PR
a version in the mean time (I didn't really think through how much of this
was automated when accepting the first homebrew package story).

**Comment by genevievelesperance** [comment]
I updated the PR on the tap with bbl 3.2.3 but, yes, access & automation would be helpful.

https://github.com/cloudfoundry/homebrew-tap/pull/34

**Comment by genevievelesperance** [comment]
The homebrew-tap is up-to-date.
https://github.com/cloudfoundry/homebrew-tap/blob/master/bbl.rb
