### ISSUE TITLE
ssh key gets generated even when `--no-director` is specified

### ISSUE THREAD

**Issue by kkallday** [cloudfoundry/bosh-bootloader#158]
When I want `bbl` to just create my infrastructure I wouldn't expect it to generate and append an SSH key to my project. No instances are being deployed so that SSH key isn't being used.

```
$ bbl up --iaas gcp --no-director
step: appending new ssh-keys for the project "my-gcp-project-id"
step: generating terraform template
step: applied terraform template
```

**Comment by zachgersh** [comment]
@kkallday - this is going to come out with a commit I will be pushing soon.
