### ISSUE TITLE
create-lbs in gcp uswest1 creates two in zone A

### ISSUE THREAD

**Issue by utricularian** [cloudfoundry/bosh-bootloader#160]
We `bbl create-lbs` in a GCP environment in uswest and looked at the Load Balances tab in Google Console. We noticed two separate LBs in the same zone.

```
Instance group	Zone	Healthy	Autoscaling	Balancing mode	Capacity
bbl-env-michigan-2017-07-10t23-54z-router-lb-0-us-west1-a	us-west1-a	0 / 0	Off	Max CPU: 80%	100%
bbl-env-michigan-2017-07-10t23-54z-router-lb-1-us-west1-b	us-west1-b	0 / 0	Off	Max CPU: 80%	100%
bbl-env-michigan-2017-07-10t23-54z-router-lb-2-us-west1-a	us-west1-a	0 / 0	Off	Max CPU: 80%	100%
```

This led to the cloud-config being created with multiple AZs pointing at the same zone, which in turn lead to some crashes while deploying CloudFoundry (crashes due to instances being in more than one zone).

It appears `us-west1` has zones `us-west1-a`, `us-west1-b`, `us-west1-c`, so correct behavior is probably to use `c` instead of that redundant `a`.

**Comment by genevievelesperance** [comment]
GCP used to only have two zones in us-west1 so we re-used a. This may have changed. We will investigate.

**Comment by zankich** [comment]
@evanfarrar When will this be released? We've hit this problem again, and would appreciate a new version with this fix.

**Comment by evanfarrar** [comment]
We're fixing it in a new and better way, the story is in flight.
