### ISSUE TITLE
--debug flag doesn't work

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#164]
I am creating new environment on GCP and want `bbl` to show debug output.

<img width="503" alt="screen shot 2017-07-24 at 9 46 31 am" src="https://user-images.githubusercontent.com/9861024/28511806-8ea8253e-7057-11e7-9029-df1cdb2f5179.png">

I get the following message

```
flag provided but not defined: -debug
```

Though in `bbl --help` I see the debugging option

```
--debug                Prints debugging output
```

**Comment by genevievelesperance** [comment]
Run 
```
bbl --debug up 
...
```

That flag is a global option, so it should go ahead of the command.
