### ISSUE TITLE
Can't deploy to all the GCP regions

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#165]
I have found that it is not possible to deploy with BBL to all the regions provided by GCP. Particularly I have failed to deploy Cloud Foundry in `europe-west2`. Cloud config does not contain availability zones in this case which prevents `cf-deployment` from deploying correctly.

I investigated the code and found out that there is a particular set of regions `bbl` is aware of: https://github.com/cloudfoundry/bosh-bootloader/blob/da5135770f7cf23ae87e7b73104bcf2dc68031a3/gcp/zones.go#L11-L16

One possible solution for this issue is to provide the list of regions in the `bbl` documentation. Another is to expand this list to all the regions GCP provides for now and keep that list in sync. And the third one is to get zone list from Google cloud API directly not relying on intermediate tables.

**Comment by evanfarrar** [comment]
We've scheduled this for this week.

**Comment by lexsys27** [comment]
Great! Here is the API [link](https://cloud.google.com/compute/docs/reference/beta/zones/list) to list all the zones available for the project.
