### ISSUE TITLE
Through an error when zone is not in the region

### ISSUE THREAD

**Issue by lexsys27** [cloudfoundry/bosh-bootloader#166]
`bbl up` accepts both `gcp-region` and `gcp-zone`. If by mistake user supplies zone outside the region the command fails with error

```
Creating VM: googleapi: Error 404: The resource 'projects/XXX/regions/europe-west2/subnetworks/YYY' was not found, notFound
```

My suggestion is to check the zone is inside the region explicitly and give the user meaningful error message.

**Comment by genevievelesperance** [comment]
This fix will be in the next bbl version.
