### ISSUE TITLE
Add BOSH_GW_USER to bbl print-env

### ISSUE THREAD

**Issue by sjolicoeur** [cloudfoundry/bosh-bootloader#169]
We've had issues `bosh ssh`-ing into our CF jobs, only to discover that the user for the jumpbox had changed from `vcap` to `jumpbox` as per the [notes for 3.2.1](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v3.2.1)

I believe this is the issue that is happening with #168

it would be great if the `bbl print-env` cmd  would export it as the `BOSH_GW_USER` so we could make it part of our env. This would make it far more intuitive to use `bosh ssh`

**Comment by evanfarrar** [comment]
sjo

1) That's surprising, as the BOSH_GW_USER should be defaulting to jumpbox

**Comment by sjolicoeur** [comment]
@evanfarrar what we saw was that none of the `BOSH_GW_*` variables were being set, but we only needed `BOSH_GW_USER=jumpbox` for things to work. 

Glad to hear there will be something better soon!
