### ISSUE TITLE
bbl breaking change 3->4: bbl --no-director deployment on GCP

### ISSUE THREAD

**Issue by markstokan** [cloudfoundry/bosh-bootloader#183]
The Toolsmiths team used bbl v3.2.6 to bootstrap our GCP environment as documented at:

 https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/advanced.md

This morning when we wanted to add a datadog api key, we found bbl v4.1.4 was unable to extract the bosh deployment variables from our bbl-state.json

```
→ bbl --version
bbl 4.1.4 (darwin/amd64)

→ bbl bosh-deployment-vars
get terraform outputs: exit status 1
```

We had to re-download the v3.2.6 binary in order to proceed.

FWIW... the full command we were using to upgrade the bosh director was:

```
→ bosh create-env bosh.yml --state ./state.json -o cpi.yml -o external-ip-not-recommended.yml -o ./jumpbox-user.yml -o ./datadog.yml --vars-store ./creds.yml -l <(bbl bosh-deployment-vars)
```

Reached out to #bbl-users slack channel and was asked to file a bug report:

 https://cloudfoundry.slack.com/archives/C2DBC3YGZ/p1503597839000184

I'm hesitant to post the bbl-state.json file because of the embedded credentials but it is checked into a private repo I can share with your team or DM directly:

 https://github.com/pivotal-cf/deployments-toolsmiths/blob/master/gcp/pcf-toolsmiths-dev-1/bbl/bbl-state.json

**Comment by nmahoney-pivotal** [comment]
We were unable to reproduce this issue. We even downloaded the `bbl-state.json` that you provided and were able to successfully call `bbl bosh-deployment-vars` with `bbl v4.1.4` and `terraform v0.9.11`. Are we misunderstanding something or is that failing on your machine?

Are you available to cross-team pair on this at some point?

**Comment by markstokan** [comment]
Please ignore this bug report.

It turns out the root cause was our team switching back to an older version of terraform (v0.8.4) for unrelated reasons.  I just swapped back to v0.10.2 and confirmed everything works.

Sorry for the false alarm!

**Comment by genevievelesperance** [comment]
Thanks for letting us know the root cause!
