### ISSUE TITLE
`bbl up` might miss a step in configuring GCP

### ISSUE THREAD

**Issue by winnab** [cloudfoundry/bosh-bootloader#184]
We have just finished working through a Pivotal onboarding tracker backlog. We're using `bbl` to create a director and load balancer and to deploy CF.

To create the load balancer, we ran the following command: `bbl create-lbs --type cf --domain <domain> --cert <cert> --key <key>` 

After deploying CF, when we were trying to target our API, we noticed that we couldn't reach any CF endpoints. We were getting a 502 error. 

We checked Google Console. On the instance detail page for the load balancer that we created with `bbl`, there was a small warning icon near the top right of the screen. Hovering over it, the warning instructed us to make sure to map the port named 'https' to a port number. We edited the instance as instructed, mapping 'https' to port 443. This resolved the issue.

We wondered if this issue was because we were using an existing project (our team's project, services-enablement) rather than a fresh GCP project. However, another pair was going through the onboarding at the same time. They used a fresh GCP environment and hit the same issue.

We suspect that there is a problem with Terraforming the load balancer. Would it be possible to configure the port mapping automatically as part of `bbl create-lbs`?

Thanks,
Winna and @nodo

**Comment by genevievelesperance** [comment]
What version of bbl?

**Comment by genevievelesperance** [comment]
This seems to have been the result of a fix for https://github.com/cloudfoundry/bosh-bootloader/issues/148.

We resolved the issue you discovered in https://github.com/cloudfoundry/bosh-bootloader/commit/48cee24fd072830b21c7be054ed00af1fb6521b6.

It should be in the next release. Thanks!
