### ISSUE TITLE
Ambiguous error messages after deleting bbl-state.json

### ISSUE THREAD

**Issue by njbennett** [cloudfoundry/bosh-bootloader#190]
So I got my bbl deployment into a bad state (I couldn't bbl destroy, got an `Expected to use variables:` error) and foolishly deleted my `bbl-state.json` file. When I tried to `bbl up` again, I see:

`It looks like a bbl environment already exists with the name 'uss-scorpion'. Please provide a different name.`

I *really* wanted an environment named 'uss-scorpion,' though, and I didn't want to leave extraneous things lying around in my GCP account. So I deleted the vm it created in the GCP GUI, tried again. Same error.

I was able to work out everything that I needed to destroy by checking the code for that error message, then running `bbl latest-error --debug` when directed to discover that the external ip also needed to be deleted.

It would have been easier and faster, however, if the error message had directed me to the specific resources that I needed to delete.

I'd be happy to make a pull request if you agree that "more help rescuing user from bad mistakes" would be useful. It looks like it'd be relatively simple to make the error messages a bit more specific.

**Comment by genevievelesperance** [comment]
Hey @njbennett!

We use the VPC check as "representative" of any terraform resources that could be in your GCP account with that environment name. It could be load balancers, external ips, health checks, routes, etc. that may be left behind by a failed terraform destroy or an accidentally deleted `bbl-state.json`.

If you want to make a PR to use the GCP client to query for those resources with that environment name, I think it would be totally helpful for the user to know where to look to clean up! (It also would keep them from deleting just the VPC, bbl'ing up, and failing again cause there are other resources.)

Let me know if you'd like to do that and we can close this issue out and wait for the PR!
