### ISSUE TITLE
Add "I know what I am doing" bosh mode

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#191]
I work with dev builds of bosh and I _really_ do not want to have to go and download another version of bosh only because bbl cannot parse my version.

It'd be nice if `bbl` could just ignore this version check when I pass a flag (or if I build bbl myself).

I pretty much rebuilt the `bbl` binary and made this code always just return `nil`

https://github.com/cloudfoundry/bosh-bootloader/blob/9d8b5e6e50dba708354e0dfe3253adc7380e4c51/commands/fail_fast_bosh_version.go#L10-L34

**Comment by genevievelesperance** [comment]
What does the dev version of bosh print?

**Comment by eitansuez** [comment]
hi, i don't know anything about dev builds of bosh cli.
i'm running a bosh cli i installed formally with homebrew.
my bosh cli version is:  version 2.0.45-d208799-2017-10-28T00:31:54Z
my bbl version was likewise installed homebrew, version: bbl 5.10.1 (darwin/amd64)
i took a first step at getting to know bbl by attempting to install a concourse.  following instructions here:
https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse-gcp.md

the first bbl command:
bbl plan --lb-type concourse

responds with:
BOSH version must be at least v2.0.24

**Comment by genevievelesperance** [comment]
We use the semver golang package so it actually removes anything after the `-` in order to compare the versions. We use homebrew and have been using that version of the bosh-cli since it was released in late October.

Is there anything else about your setup you can tell us?

**Comment by genevievelesperance** [comment]
The dev verison of the bosh-cli prints `version [DEV BUILD]`.

We can throw an error if the version does not meet the constraint or the version cannot be parsed properly. @zachgersh how have you gotten around this issue thus far? Using only the latest release of the bosh-cli?

**Comment by genevievelesperance** [comment]
@zachgersh I installed a dev version of bosh and bbl logs a warning (`warning: BOSH version could not be parsed`) but does continue. I'm going to close this issue!

**Comment by eitansuez** [comment]
> Is there anything else about your setup you can tell us?
there must be.  i brew uninstalled both bbl and bosh-cli and reinstalled.  not sure why i get this error message.  thanks for the advice.

**Comment by eitansuez** [comment]
figured it out.  thanks again for the tip. it looks like i had an errant symlink somewhere..
