### ISSUE TITLE
AWS AMI not available in ap-south-1

### ISSUE THREAD

**Issue by varun7447** [cloudfoundry/bosh-bootloader#200]
Facing issue when the AWS region is set to ap-south-1. As there are no AMI in this region. Is there a reason or no on has requested. The issue happen when running bbl up in this region.

**Comment by genevievelesperance** [comment]
We tried including the AMI for that region but the requests we made seemed to be frequently unresponsive. We presumed that as a new region it may not be reliable yet and so did not add the AMI to our list in bbl. We can check if it is more reliable now.

**Comment by varun7447** [comment]
Thanks i see that it is added now. Also wondering if ca-central-1 has the same reason why we did not add because of the stability issues in the region?

**Comment by genevievelesperance** [comment]
That region was not around the last time we checked for AMIs. We can add it now.

**Comment by varun7447** [comment]
I guess there are lot of new regions. Is there any criteria for adding the
new region?

**Comment by genevievelesperance** [comment]
We add regions as we know about them and determine if they are stable.

Let us know if there are any others. Added ca-central-1.
