### ISSUE TITLE
Consider terraform-secure-backend to store bbl tf state

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/bosh-bootloader#202]
Following up upon 
https://github.com/cloudfoundry/pmc-notes/blob/master/Runtime/2017/2017-10-03-runtime.md#bosh-bootloader-aka-bbl mentions
`We are beginning to refactor how state is stored. [...] . If you interact with BBL’s state director outside of bbl, we are interested in talking to you.
`

While not yet interacting with BBL TF state outside of BBL, we would be interested in leveraging BBL terraform config file in the future, in particular with upcoming openstack support in #77 

We've been working on a way for terraform to support writing to credhub. @ArthurHlt produced the following implementation of the terraform http backend backed by credhub:
https://github.com/orange-cloudfoundry/terraform-secure-backend

Similarly, https://github.com/orange-cloudfoundry/terraform-provider-credhub provides support for credhub credentials as tf resources or data sources. This is still early work, and we're welcoming feedback. 

I'm wondering whether this could be something of interest in the context of the current state refactoring in bbl.

**Comment by gberche-orange** [comment]
thanks @evanfarrar for your detailed response! We're glad you see some potential uses for the terraform credhub backend. We're looking forward to the terraform config extraction and customization hooks.

**Comment by evanfarrar** [comment]
We have made it possible to configure an external store for the terraform state, and now have a plan-patch published demonstrating this.

We will continue look for ways to make external storage of the terraform state the default.
