### ISSUE TITLE
wiring up DNS zone in GCP

### ISSUE THREAD

**Issue by jasonkeene** [cloudfoundry/bosh-bootloader#203]
When bbl creates our DNS zone it uses a different set of Google's nameservers. This means every time we destroy the environment and re-run `bbl up` we then have to manually re-wire the nameservers we delegate to for that zone.

This is kind of a limitation in GCP but I know for certain I can manage all of this using raw terraform. It would be nice if we had a solution that eliminates this manual step.

@enocom

**Comment by genevievelesperance** [comment]
@jasonkeene Until we address this in the terraform templates, you can add a task to your CI (if this is where you are creating/destroying bbl environments), that looks like ours for managing gcp dns: https://github.com/cloudfoundry/infrastructure-ci/blob/master/scripts/common/manage-gcp-dns/task

**Comment by evanfarrar** [comment]
We took a stab at this, and due to [this terraform issue](https://github.com/hashicorp/terraform/issues/16380) it turned out to be really difficult to fully automate this step by utilizing the zones in a user's account. We are going to put it down for now and re-attempt later.
