### ISSUE TITLE
bbl 4.10.3 returning incorrect version

### ISSUE THREAD

**Issue by tcrockett1138** [cloudfoundry/bosh-bootloader#206]
bbl v4.10.3 appears to be returning the incorrect version string.

`bbl -v`
`bbl dev (darwin/amd64)`

As I believe 4.10.3 is the current release, not a dev release, I would expect a version string similar to 4.10.2.

`bbl -v`
`bbl 4.10.2 (darwin/amd64)`
or Linux
`bbl 4.10.2 (linux/amd64)`

**Comment by genevievelesperance** [comment]
This happened only with `4.10.3` as it was created by hand for a specific issue and not in our CI. This is not an issue in versions before or after (`4.10.4+`).

**Comment by tcrockett1138** [comment]
Thanks!  :-)
