### ISSUE TITLE
[aws] Ohio/us-east-2 region only has newer instance types

### ISSUE THREAD

**Issue by drnic** [cloudfoundry/bosh-bootloader#210]
Heads up to anyone deploying to ohio/us-east-2:

I was getting very unhelpful error messages from AWS with the aws `cloud-config.yml` ideas in this repo. 

```
Task 150 | 05:28:26 | Creating missing vms: diego-cell/71bfb2e8-7c71-4973-bc55-4959aa0b7349 (0) (00:01:23)
Task 150 | 05:28:26 | Error: Unknown CPI error 'Unknown' with message 'The requested configuration is currently not supported. Please check the documentation for supported configurations.' in 'create_vm' CPI method
```

It turns out that Ohio region only has newer families of instance types, e.g. `m4.large`, `r4.xlarge`, and `c4.large`.

**Comment by varun7447** [comment]
Same problem in ca-central-1 region. Opened an issue with cf-deployment https://github.com/cloudfoundry/cf-deployment/issues/338

**Comment by genevieve** [comment]
I think we have changed the instance types since this. We will also be moving towards  the calculated vm types. 

If you ever blocked by a cloud-config choice in bbl, you can provide an ops-file in `bbl-state-dir/cloud-config/your-ops-file.yml` that will be applied in the next `bbl up`.
