### ISSUE TITLE
bbl destroy fails if the network name is the substring of another used network

### ISSUE THREAD

**Issue by edwardecook** [cloudfoundry/bosh-bootloader#212]
We have two bbl environments `drats-two-envs-restore` and `pdrats-two-envs-restore`. If I try to bbl destroy the former then the command fails with "bbl environment is not safe to delete; vms still exist in network:" and a list of vms all belonging to the `pdrats-two-envs-restore` environment. We think this is due to the following code block: https://github.com/cloudfoundry/bosh-bootloader/blob/93d4a92591729f6a98ab2296f243ca40e409e309/gcp/client.go#L103-L105.

The specific command being run is `bbl --debug destroy --no-confirm --skip-if-missing` from the cf-deployment-concourse-tasks repo.
cc @gcapizzi

**Comment by genevievelesperance** [comment]
Hey Ed, this was released in `bbl v5.6.0`.
