### ISSUE TITLE
Support for allowing terraform outputs to be interpolated into `bosh create-env`

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#220]
## Use case

We like to deploy a bosh-director with a co-located credhub where credhub stores its creds in an external database. It would be great if we could:
1. run `bbl plan` to generate the base templates
1. add a `create-sql-db_override.tf` to create the DB with new TF outputs called `external_db_host` etc.
1. add an ops file called `credhub-external-db.yml` with placeholders for `external_db_host`
1. run `bbl up`
1. see that `bbl up` correctly interpolated terraform outputs into the `bosh create-env` deploy

Maybe generically any terraform output that starts with `bosh_director_*` prefix gets passed as a flag to `bosh create-env` but up to y'all.

**Comment by genevievelesperance** [comment]
We are merging this PR #236 and it allows you to specify terraform outputs in your overrides/additional templates that get passed through to `bosh create-env`.

For the jumpbox, you can prepend those outputs with `jumpbox__`.
For the director, you can prepend those outputs with `director__`.

Does this work for you? 

It will be out in the next release.

**Comment by ljfranklin** [comment]
Sweet, looks good to me! Hopefully we'll give it a spin soon and report back.
