### ISSUE TITLE
Feature Request: bbl Concourse resource

### ISSUE THREAD

**Issue by ljfranklin** [cloudfoundry/bosh-bootloader#221]
## Motivation

Currently anyone that uses Concourse and BBL will be writing pipelines and bash scripts that do something like the following:

1. download the bbl state from S3 or similar
1. untar it
1. run `bbl up` in a task
1. retar
1. finally reupload back to S3.

But what happens if `bbl up` fails halfway through? Did you remember to run the retar in a `trap` so that it runs even on error? Did you remember to have the S3 upload run in an `ensure` block in your pipeline? If not, your state is lost and you'll need to do manual bbl surgery to get things back in a good state.

While shared tasks like [cf-deployment-concourse-tasks](https://github.com/cloudfoundry/cf-deployment-concourse-tasks) helps, it is somewhat inflexible such as requiring bbl state to be stored in git rather than S3. A more robust bbl-resource would save us some pain in the long-run.

**Comment by evanfarrar** [comment]
We'll talk it over a bit in our team. Currently most of the core CF teams use BBL via cf-deployment-concourse-tasks, but I've recently discovered that a great many other users use BBL by hand right now. One key factor will be if we can also refactor cf-deployment-concourse-tasks to use this proposed resource.

Another alternative we have explored was to genericize cf-deployment-concourse-tasks to be "make director and deploy bosh release to it -tasks". Our team, for example, needs to test how accurately bbl integrates with concourse (evanfarrar/concourse-deployment) and we forked cf-deployment-concourse-tasks to do so. How would that work for your use case? What if cf-deployment-concourse tasks were extended to optionally store in s3?

**Comment by ljfranklin** [comment]
@evanfarrar I won't speak for @dsabeti and rel-int, but if I were them I wouldn't want to be in the business of maintaining a lot of complex bash scripts which are highly configurable with different backends and config options. Those tasks can't be tested with the same rigor that a resource written in Go can be and tasks are inherently less flexible than resources.

My two cents, Concourse is built to model stateful interactions via resources, not tasks. I think the cf-deployment-concourse-tasks are already feeling this friction, e.g. [ops-files](https://github.com/cloudfoundry/cf-deployment-concourse-tasks/blob/bec3b095ee5392717cc975d8cca1d8bd4f31004f/bbl-up/task.yml#L13). If you want no ops files you need to pass a dummy input, if you want multiple ops file directory you have to write a separate task to merge them together into one dir.

**Comment by mcwumbly** [comment]
There's probably a better place for the meta "tasks vs. resources" discussion, but I'm not sure offhand where that is, so here goes (my 2 cents):

>  tasks are inherently less flexible than resources.

One thing I like about tasks is that they have outputs which can be consumed easily by downstream tasks.  that's a feature I don't believe you get from resources.

> tasks can't be tested with the same rigor that a resource written in Go can

Tasks *could* be written in Go if this were a big enough concern

> My two cents, Concourse is built to model stateful interactions via resources, not tasks.

I've heard this before, but I'm not sure I fully understand the distinction, particularly when the side-effect does not create a versioned artifact.  When it is impossible for something else to "get" a prior version of the resource, I'm not sure it is that helpful to model it this way. 

>  I think the cf-deployment-concourse-tasks are already feeling this friction, e.g. ops-files.

This is annoying, I agree.  But it's not clear to me that the trade-offs of switching from tasks to resources are worth it.  Is it possible there's just a missing feature here for tasks in concourse?

I think looping in @dsabeti makes sense.

He and I spoke about tasks vs. resources a while back, and I know it's a larger conversation.  It seems like it makes sense for `bbl` and the other `cf-deployment-concourse-{tasks|resources}` to follow suit with each other.

**Comment by ljfranklin** [comment]
@mcwumbly agreed that this is a meta discussion that could get into the weeds. That said, let's do it anyway :)

> One thing I like about tasks is that they have outputs

Not sure I understand. Resources have a single output directory to put their build artifacts, e.g. a `get: my-git-repo` or `put: my-git-repo` will populate an output directory called `my-git-repo` with your files from github.

> Tasks could be written in Go if this were a big enough concern

Agreed, would love to see less bash and more TDD'ed Go in CI.

> When it is impossible for something else to "get" a prior version of the resource, I'm not sure it is that helpful to model it this way.

While being able to run against a previous version of a resource is certainly valuable, I see resources as having several other benefits:
- The resource interface (`get` and `put`) model stateful interactions in an understandable way. I can only mutate with a `put`, a `get` is non-mutating and idempotent. With a task, who knows. Maybe it had a side-effect, maybe it didn't. You could name tasks carefully like `get-bbl-state` and `update-bbl-state`, but this is not enforced.
- Resources can take config options as yaml in pipeline.yml, tasks can only take env vars as flat strings. Similarly common resource options can go under `source` while others go under `get.params` or `put.params` for a nice separatation.
- You know that a `put` to a resource will persist your changes. With a task, you don't know whether it saved your state to S3 directly or whether you need to follow the task with a `put: s3-file`. And you better remember to nest that `put` under an `ensure` to avoid losing state in the failure case.
- Resources can take a variable number of input dirs

I'm sure there are some valid exceptions, but living in a world where all tasks are side-effect free and idempotent and all stateful interactions are done with resources seems much easier to reason about.

At the risk of going off the rails even more, pinging @vito to see if the limitations of tasks are a missing feature or intentional.

**Comment by mcwumbly** [comment]
> `put: my-git-repo` will populate an output directory called my-git-repo with your files from github

Oh, interesting. I didn't realize that put gave you immediate access to the output as well.  Maybe that addresses my main concern.

---

What do you think the proper way to model deleting a bbl-environment would be with a resource?

**Comment by ljfranklin** [comment]
Yep, each `put` is followed by an implicit `get` in Concourse.

> What do you think the proper way to model deleting...

_pounds desk_ I've been waiting for a `delete` step for like a year and a half: https://github.com/concourse/concourse/issues/534. Sounds like that issue is moving again but for the terraform-resource I ended up with this nonsense:

```
put: terraform
params:
  action: destroy
get_params:
  action: destroy
```

**Comment by joshzarrabi** [comment]
This is done: https://github.com/cloudfoundry/bbl-state-resource
