### ISSUE TITLE
The link to `GCP - Deploying Cloud Foundry` in the README is broken.

### ISSUE THREAD

**Issue by mavenraven** [cloudfoundry/bosh-bootloader#222]

**Comment by genevievelesperance** [comment]
Updated, thank you!

**Comment by mavenraven** [comment]
thanks @genevievelesperance!

**Comment by mavenraven** [comment]
Wait, actually, where's the instructions for using bbl with GCP?

**Comment by genevievelesperance** [comment]
[Here are instructions](https://docs.cloudfoundry.org/deploying/cf-deployment/gcp.html) for deploying cf-deployment to GCP with bbl

**Comment by mavenraven** [comment]
ah cool, thanks!

**Comment by genevievelesperance** [comment]
You can reach out to us in [#bbl-users](https://cloudfoundry.slack.com/messages/C2DBC3YGZ/details/) if you have any questions.
