### ISSUE TITLE
Feature Request: add vsphere as IaaS provider

### ISSUE THREAD

**Issue by patrickhuber** [cloudfoundry/bosh-bootloader#225]
I saw the CF summit talk on BBL and noted the point where VMWare wasn't supported due to terraform support. Can we list out the incompatibility here so that they can be tackled by the terraform and bbl community?

**Comment by evanfarrar** [comment]
v5.7.0 adds vSphere support, though it is not mentioned in the online help (yet). We have realized the benefits of vSphere support even without paving support from terraform: it helps users that operate bosh on multiple IaaSes to have a single unified way of targeting their BOSH directors and updating them.

We suspect that it is much better to target NSX-T for setting up the network, network security rules, and load balancers, so we have begun to explore that. Please try out 5.7.0 as it exists and let us know what you think though.
