### ISSUE TITLE
bbl up deletes load balancer unless you pass in hidden lb-type flag

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/bosh-bootloader#226]
While attempting to update our concourse `bbl` director from bbl 4.7.0 to 5.5.0, running `bbl up` unexpectedly tore down our load balancer. We could not figure out why from any documentation, and when we asked on slack for help, it was suggested we pass in an `lb-type` flag, which *does not* show up when you run `bbl up -h`, which worked. It was suggested that this was an issue because we passed in opsfiles to our bbl command. 

It would be great if `bbl` warned you before deleting your load balancer, and if all flags showed up in the help menu.

**Comment by jvshahid** [comment]
i think `--cert` and `--key` don't show up in the help menu either

**Comment by genevievelesperance** [comment]
Hey @joshzarrabi.

On the former: `bbl up` deleting your load balancers when you don't pass the flags is a bug and is fixed. It will be in the next release.

On the latter: `bbl up` and `bbl plan` were missing consistent documentation on the load balancer options and are now in `bbl v5.8.0`.

**Comment by joshzarrabi** [comment]
Thanks @genevievelesperance
