### ISSUE TITLE
Please set security group "Group Name" the same as "Name"

### ISSUE THREAD

**Issue by nmahoney-pivotal** [cloudfoundry/bosh-bootloader#229]
![names-are-hard](https://user-images.githubusercontent.com/12817808/33779622-808dd1c6-dc02-11e7-968d-f1f9808d56b1.png)

Would it be possible to set the "Group name" to be the same as the "Name"?
The terraform-generated name is not super useful.

@rosenhouse

**Comment by evanfarrar** [comment]
We've avoided this so far because the name change will force a recreate. We could schedule this for a breaking change, but everybody with existing environments would have to tear them down.

**Comment by genevievelesperance** [comment]
We can do it only for the isolation segments security group since users have been able to find aws security groups by their Name and not their GroupName thus far.

**Comment by genevievelesperance** [comment]
Hey Nick, this will be in the next release!
