### ISSUE TITLE
bbl version mismatch on `print-env` produces unactionable error regarding schema version

### ISSUE THREAD

**Issue by emalm** [cloudfoundry/bosh-bootloader#231]
I ran `bbl print-env` with my local `bbl` at version v5.3.6 against an environment that had been created with a more recent version (unbeknownst to me, v5.7.3). This command failed with the following error:

```
Existing bbl environment was created with a newer version of bbl. Please upgrade to a version of bbl compatible with schema version 13.
```

None of the release notes refer to this "schema version", though, so I was unable to use this information to determine a suitable version to which to upgrade. I eventually upgraded to the latest published version (v5.7.4) and that worked.

I would suggest either changing the error to recommend upgrading to the latest published version, without being specific about schema version compatibility, or publishing the range of compatible schema versions on each bbl release so that I can select a suitable one after receiving this error.

Thanks,
Eric

**Comment by evanfarrar** [comment]
Versions 5.4 and above record their version into the state file, and use this to generate a more helpful error message. Unfortunately, version 5.3 doesn't know about this field in the state.json and ignores it, but if you tried this with 5.4 it would have explicitly told you to try 5.7.3 instead (provided the JSON schema had changed in the intervening time).

https://github.com/cloudfoundry/bosh-bootloader/blob/master/storage/bootstrap.go#L66

**Comment by emalm** [comment]
Thanks, @evanfarrar !
