### ISSUE TITLE
compiling package 'bosh_aws_cpi...' failed

### ISSUE THREAD

**Issue by TCSCMAPIVOTAL** [cloudfoundry/bosh-bootloader#232]
#bbl up --aws-access-key-id ******** --aws-secret-access-key ******** --aws-region us-east-2 --iaas aws

Started installing CPI
  Compiling package 'ruby_aws_cpi/5e8696452d4676dd97010e91475e86b23b7e2042'... Finished (00:00:00)
  Compiling package 'bosh_aws_cpi/c2563067cbc20e3406ea36ca2984df2f0eaebcb0'... Failed (00:00:02)
Failed installing CPI (00:00:02)

Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler is older than the version that created the lockfile. We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing json 1.8.3 with native extensions
Installing mini_portile2 2.1.0
Installing pkg-config 1.1.7
Installing little-plugger 1.1.4
Installing multi_json 1.12.1
Installing semi_semantic 1.2.0
Installing membrane 1.1.0
Installing httpclient 2.7.1
Using bundler 1.11.2
Installing nokogiri 1.6.8 with native extensions

Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
.
..
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.

# gem install nokogiri -v '1.6.8'
-Successfully installed nokogiri-1.6.8
Parsing documentation for mini_portile2-2.1.0
Installing ri documentation for mini_portile2-2.1.0
Parsing documentation for pkg-config-1.1.9
Installing ri documentation for pkg-config-1.1.9
Parsing documentation for nokogiri-1.6.8
Installing ri documentation for nokogiri-1.6.8
Done installing documentation for mini_portile2, pkg-config, nokogiri after 2 seconds
3 gems installed

I am listing the various versions that I am using - 

[root@ip-172-31-12-166 bin]# aws --version
aws-cli/1.11.132 Python/2.7.12 Linux/4.9.62-21.56.amzn1.x86_64 botocore/1.5.95

[root@ip-172-31-12-166 bin]# bbl --version
bbl 5.7.4 (linux/amd64)

[root@ip-172-31-12-166 bin]# terraform --version
Terraform v0.11.1

[root@ip-172-31-12-166 bin]# bosh --version
version 2.0.45-d208799-2017-10-28T00:31:53Z

Succeeded

[root@ip-172-31-12-166 bin]# ruby -version
ruby 2.4.3p205 (2017-12-14 revision 61247) [x86_64-linux]

[error.txt](https://github.com/cloudfoundry/bosh-bootloader/files/1562384/error.txt)

**Comment by genevievelesperance** [comment]
Hi @TCSCMAPIVOTAL. We haven't seen this issue but I believe you could run `xcode-select --install` before the bbl command and you may get unblocked.
