### ISSUE TITLE
Jumpbox stemcell should be up to date

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/bosh-bootloader#238]
When running `bbl up` with bbl version 5.11.4 on gcp, we noticed that the jumpbox stemcell was on version 3421.15. It should be updated along with the director stemcell.

Relevant logs:
```
Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-google-kvm-ubuntu-trusty-go_agent/3421.15'... Skipped [Stemcell already uploaded] (00:00:00)
...
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Succeeded
step: created jumpbox
```

**Comment by evanfarrar** [comment]
That is the version that jumpbox-deployment uses:

https://github.com/cppforlife/jumpbox-deployment/blob/master/gcp/cpi.yml

What version were you hoping for? I can open a PR to that repo, which, when merged, will trigger our pipelines to make a patch release.

**Comment by joshzarrabi** [comment]
@evanfarrar sure, it seems like the owner of the repo should be doing this themselves though,

**Comment by genevievelesperance** [comment]
The stemcell was bumped in jumpbox-deployment and that will get pulled in to the next release of bbl. Thanks!
