### ISSUE TITLE
bbl AWS IAM policy too broad

### ISSUE THREAD

**Issue by loewenstein** [cloudfoundry/bosh-bootloader#239]
Looking at https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-aws.md#creating-an-iam-user in particular the 

```
iam:*
```

looks far too broad. If I am not mistaken this effectively creates a user that can escalate it's privileges.

**Comment by evanfarrar** [comment]
The permissions are rather broad, however the `iam:*` permissions are used to create an IAM role and instance profile for BOSH with more limited abilities. The credential supplied to bbl is only used while BBL is running, so you can feel free to delete it when you are not using it. Admittedly, even for that activity `*` is more than it needs,  so in the documentation I will limit this to at least the specific activities we do: read/create/delete iam role, attach to instance profile, etc.

I have considered providing the ability to instead supply two different IAM users: one user that has just the permissions that bbl will use to create networks/vms/security-groups/etc and one user that has just the permissions that BOSH needs to create VMs/disks/etc. If you successfully supplied both of these instead, BBL would not demand a single user with `iam:*`. Would this be more preferable to you?

Unless you have a different workaround in mind?

**Comment by evanfarrar** [comment]
I've made the role more limited now. The more accurate permissions now are "only" these:
```
iam:AddRoleToInstanceProfile
iam:AttachRolePolicy
iam:CreateInstanceProfile
iam:CreatePolicy
iam:CreateRole
iam:DeleteInstanceProfile
iam:DeletePolicy
iam:DeleteRole
iam:DetachRolePolicy
iam:GetInstanceProfile
iam:GetPolicy
iam:GetPolicyVersion
iam:GetRole
iam:ListAttachedRolePolicies
iam:ListInstanceProfilesForRole
iam:ListPolicyVersions
```

Closing for now, but still open to feedback on other approaches.

**Comment by loewenstein** [comment]
@evanfarrar I like the idea of two separate IAM users. 
I suspect even with the now limited permissions I could still escalate privileges and get account admin permissions.

**Comment by will-gant** [comment]
Just for anyone else still using `bbl` who also wants to be more specific with IAM permissions, in addition to those listed above you also now need:

```
iam:GetServerCertificate
iam:GetRolePolicy
iam:PutRolePolicy
iam:PassRole
iam:UploadServerCertificate
```
