### ISSUE TITLE
Bosh director's additional disk size of 32G is too small for cf-deployment

### ISSUE THREAD

**Issue by nimakaviani** [cloudfoundry/bosh-bootloader#243]
From our investigation of an environment in Diego, it appears that an active deployment of CF pulls down 27G of blobs on the director disk.

The default disk size of 32GB defined in bosh-deployment opsfile [HERE](https://github.com/cloudfoundry/bosh-deployment/blob/c7fa3da00a84b59853e0f76d2504df23cbd5c1b5/bosh.yml#L19-L21) appears to be too small for cf deployments.

We had a discussion with @genevievelesperance regarding the issue and we think it would be a good if bbl increases the default disk size, to e.g. 100GB through an ops-file and at the time of deployment.

**Comment by genevieve** [comment]
This will be in the release of bbl!
