### ISSUE TITLE
bbl up fails on Azure (public IPs not available)

### ISSUE THREAD

**Issue by zmb3** [cloudfoundry/bosh-bootloader#245]
I downloaded the v6.0 binary from the releases page and tried to do a `bbl plan` + `bbl up` on Azure.  The `bbl up` step fails with the following errors:

```
Error: Error applying plan:

3 error(s) occurred:

* output.external_ip: Resource 'azurerm_public_ip.bosh' does not have attribute 'ip_address' for variable 'azurerm_public_ip.bosh.ip_address'
* output.jumpbox_url: Resource 'azurerm_public_ip.bosh' does not have attribute 'ip_address' for variable 'azurerm_public_ip.bosh.ip_address'
* output.director_address: Resource 'azurerm_public_ip.bosh' does not have attribute 'ip_address' for variable 'azurerm_public_ip.bosh.ip_address'
```

I tore everything down, went back to v5.11.5, re-planned, and got the same result.  It seems this may be related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/310.

**Comment by genevievelesperance** [comment]
We haven't seen that issue locally. I'll try to reproduce and potentially add their `depends_upon` workaround!

**Comment by genevievelesperance** [comment]
That issue seems to be releated to dynamically allocated IPs. We chose static allocation so the resource should be available at the time that the outputs are printed during `terraform apply`. We can try creating the data source for it and then the output can depend on it.

**Comment by genevievelesperance** [comment]
I reverted to terraform azure provider `v1.0.0` and got a bbl environment. This seems to be tied to the latest release of the provider.

**Comment by zmb3** [comment]
I’ll check which version I was running locally as soon as I get to the office. We’re you able to reproduce with 1.1.0 then?

**Comment by genevievelesperance** [comment]
Yes, reproduced.

**Comment by genevieve** [comment]
Made a PR to the azure provider here: https://github.com/terraform-providers/terraform-provider-azurerm/pull/772

**Comment by genevieve** [comment]
We pinned the provider temporarily and this will be out in the next release of bbl!
