### ISSUE TITLE
Build failure on 32-bit platforms

### ISSUE THREAD

**Issue by dumbbell** [cloudfoundry/bosh-bootloader#246]
On 32-bit platforms, bosh-bootloader fails to build with the following error:

```
bosh/ip.go:55:16: constant 4278190080 overflows int
```

As a maintainer of the FreeBSD package, I prepared a [patch to fix the build failure](https://svnweb.freebsd.org/ports/head/net/bosh-bootloader/files/patch-bosh_ip.go?view=markup&pathrev=460380). However, I'm not a Go developer and I'm not sure this is the right approach. I suppose the `ip` member of the `IP` struct could be changed to an `uint32` but I have no idea what the impact would be elsewhere.

**Comment by evanfarrar** [comment]
Hey @dumbbell this is resolved. As of BBL 6.1 we have begun testing that our builds can cross-compile to 32-bit before releasing them. If you'd like, we could publish this 32bit linux build, but I imagine ports are usually meant to build locally.

**Comment by dumbbell** [comment]
Thank you! I confirm that BBL builds fine on FreeBSD 32-bit without the patch.

FreeBSD provides prebuilt packages, which is the preferred way to install applications now. Therefore, there is no need for you to publish the 32-bit Linux executable, thanks! Also, using the native executable is better.
