### ISSUE TITLE
BBL_ENV_NAME and BBL_STATE_DIR variables

### ISSUE THREAD

**Issue by karampok** [cloudfoundry/bosh-bootloader#247]
Hi, I have been start looking at bbl, it is a great tool.

I have a question about the BBL_ENV_NAME and BBL_STATE_DIR variables.
I cannot make them work.  I have to  always pass the `--state-dir` and `--name`
arguments. Am I missing something?

thanks!

(bbl 5.11.5 (darwin/amd64) )

**Comment by genevieve** [comment]
Hey! 

- There is no environment variable for `--name` that is passed to `bbl up` and `bbl plan`.
- `BBL_STATE_DIRECTORY` wasn't introduced in `bbl 5.11.5` but it is in `bbl v6`.

**Comment by karampok** [comment]
Hey Gen!

is it possible to introduce also the BBL_ENV_NAME? it will help when you work with many envs and have an identified name (to give accountability in aws/gcp).

**Comment by evanfarrar** [comment]
Hey Karampok,

I think our worry originally was that by allowing BBL_ENV_NAME you might accidentally target an environment implicitly. But BBL_STATE_DIR was omitted for similar reasons, and no one has fallen for this bit of user error so far.  We will prioritize a story to introduce BBL_ENV_NAME.

**Comment by karampok** [comment]
cool, thx!
