### ISSUE TITLE
New homebrew packages for bbl breaking changes?

### ISSUE THREAD

**Issue by staylor14** [cloudfoundry/bosh-bootloader#248]
Would you consider creating a separate homebrew version for each breaking change you release?  

Hombrew doesn't make it easy to pin to a particular version.  Apparently the way folks deal with this is to create a separate package for new versions.  For bbl, that would mean a bbl5 and a bbl6 package, 
e.g.

**Comment by cwlbraa** [comment]
@staylor14 are `brew pin` and `brew link` not sufficient?
