### ISSUE TITLE
bbl print-env not printing correct credhub variables

### ISSUE THREAD

**Issue by christianang** [cloudfoundry/bosh-bootloader#249]
Version: bbl 6.0.1 (darwin/amd64)

Ran `bbl print-env` and the `CREDHUB_USER` was wrong and the `CREDHUB_PASSWORD` was blank.

Looking at https://github.com/cloudfoundry/bosh-deployment/blob/master/credhub.yml#L79-L87. The user is now a client and it is called `credhub-admin` and the password is now under `credhub_admin_client_secret`. Environment variables have also been changed to: `CREDHUB_CLIENT` and `CREDHUB_SECRET`.

**Comment by genevieve** [comment]
Yeah we have a story for it! https://www.pivotaltracker.com/story/show/154581884

Thanks!

**Comment by genevieve** [comment]
Made the fix and it'll be in the next release!

**Comment by christianang** [comment]
Quick. 🥇

**Comment by genevieve** [comment]
Always.
