### ISSUE TITLE
Not able to deploy bosh directory in AWS linux

### ISSUE THREAD

**Issue by nishanthmehta** [cloudfoundry/bosh-bootloader#253]
AWS linux version: Amazon Linux AMI 2017.09
bbl: 5.11.5.
ruby version: ruby 2.4.1
Gem version: 2.6.14
Nokogiri: /home/ec2-user/.rvm/gems/ruby-2.4.1/gems/nokogiri-1.6.8/

Getting below error while following steps given in https://docs.cloudfoundry.org/deploying/common/aws.html#create-infra-bosh
=====error=====
To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /home/ec2-user/.bosh/installations/83b7dc83-d235-47ba-5c54-c89a4c7e8b97/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/nokogiri-1.6.8/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /home/ec2-user/.bosh/installations/83b7dc83-d235-47ba-5c54-c89a4c7e8b97/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/gems/nokogiri-1.6.8 for inspection.
Results logged to /home/ec2-user/.bosh/installations/83b7dc83-d235-47ba-5c54-c89a4c7e8b97/packages/bosh_aws_cpi/vendor/bundle/ruby/2.2.0/extensions/x86_64-linux/2.2.0-static/nokogiri-1.6.8/gem_make.out
Installing logging 1.8.2
An error occurred while installing nokogiri (1.6.8), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.6.8'` succeeds before bundling.
', stderr: '+ set -e -x

Unfortunately i am not able to find the log file in the specified directory mkmf.log.
I also tried installing nokogiri manually still getting same error.
Any help on this regard will be helpful.

**Comment by genevieve** [comment]
Hi @nishanthmehta. 

Do you have the following dependencies: https://bosh.io/docs/cli-env-deps.html?
Are you on os x?

I found a related issue here: https://github.com/SlatherOrg/slather/issues/227

As this is an issue with bosh, you might get a better response in github.com/cloudfoundry/bosh
