### ISSUE TITLE
"BOSH version must be at least v2.0.48" when bosh is v2.0.48

### ISSUE THREAD

**Issue by jenspinney** [cloudfoundry/bosh-bootloader#260]
## Problem summary
When we run `bbl up`, we see an error message say "BOSH version must be at least v2.0.48", even though our bosh CLI version is "2.0.48-e94aeeb-2018-01-09T23:08:08Z".

## Cause
After some digging, we realized this error is caused because we have an old `bosh2` executable on our machines that we don't use. We use `bosh` as the command to use the new go-based bosh CLI. When BBL tries to find the BOSH CLI executable, it first looks to see if an executable with the name of `bosh2` can be found, and if so, uses it immediately, even if it's older than the `bosh` executable. ([Relevant code here](https://github.com/cloudfoundry/bosh-bootloader/blob/master/bosh/command.go#L19-L34))

## Repro steps
Prereqs:
```
→ bosh --version
version 2.0.48-e94aeeb-2018-01-09T23:08:08Z

→ bosh2 --version
version 2.0.28-cb77557-2017-07-11T23:04:15Z

→ bbl -v
bbl 6.2.2 (darwin/amd64)
```

Then run:
```→ bbl up --lb-type=concourse```
and see the following output:
```BOSH version must be at least v2.0.48```

The error message is confusing and it took us a while to dig around and find the problem. This should either be fixed so that it doesn't rely on bosh2 before bosh, or it should pick the bosh with the newest version, or at least provide a better error message.

Thanks!
Jen and @ablease

**Comment by genevieve** [comment]
We are going to indicate which path we are using in the error message as we want to continue supporting the default usage of `bosh2` over `bosh`. This will be in the next release! Thanks.
