### ISSUE TITLE
Connection reset by peer on every bbl up

### ISSUE THREAD

**Issue by aaronjwood** [cloudfoundry/bosh-bootloader#267]
I'm trying to spin up a cluster in AWS which keeps failing at the same step every time:

```
bbl up --aws-access-key-id $AWS_ACCESS_KEY_ID --aws-secret-access-key $AWS_SECRET_ACCESS_KEY --aws-region $AWS_DEFAULT_REGION --iaas aws
...
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'jumpbox/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@MYIP:MYPORT/agent: read tcp MYIP:MYPORT->MYIP:MYPORT: read: connection reset by peer

Exit code 1
```

It seems strange that the connection gets reset each time at the same stage. I've installed everything via [brew](https://github.com/cloudfoundry/bosh-bootloader#install-bosh-bootloader-using-a-package-manager) and I'm just following [the docs.](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-aws.md#creating-infrastructure-and-bosh-director)

**Comment by genevieve** [comment]
Since this was a networking issue, I am going to close this.
