### ISSUE TITLE
Feature Request `bbl manifest`

### ISSUE THREAD

**Issue by wfernandes** [cloudfoundry/bosh-bootloader#274]
This command should print out the manifest used to deploy the director.

This would be extremely useful to help troubleshoot an environment if there were certain configurations at the director level that would need inspection at a later time. 
This could also be useful to know if other ops-files were applied during time of creation.

**Comment by genevieve** [comment]
Hey @wfernandes. That sounds like a good idea. It would essentially convert what is in `create-director.sh` from a `bosh create-env` to a `bosh interpolate` with all of the ops-files and creds specified in that script. Does that help unblock you seeing your current director's manifest?

**Comment by wfernandes** [comment]
@genevieve Thanks for the quick response.

Yes, for now I can modify the `create-env` command and add in the necessary env vars to generate the manifest.
But I'd still love to have the `bbl manifest` command. If I get the chance, I'll try and do a PR if possible.

**Comment by evanfarrar** [comment]
Is this possibly an open issue on BOSH that you could bump? (hint: it is)

**Comment by genevieve** [comment]
Tried to looking through bosh and bosh-cli issues and couldn't find the one you are referencing. Could you link to it here?

**Comment by evanfarrar** [comment]
I guess I was mistaken, I have only seen this request in slack

**Comment by genevieve** [comment]
Sounds like a great feature request in bosh though. @wfernandes Could you open this in the bosh-cli?

**Comment by zachgersh** [comment]
@wfernandes - going to close this in lieu of the discussion that is happening over on the bosh issue. If they ever do support it (sounds unlikely) we can reopen this issue.
