### ISSUE TITLE
The azure app gateway probe points to api.${var.env_id}.${var.system_domain} instead of api.${var.system_domain}

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-bootloader#280]
https://github.com/cloudfoundry/bosh-bootloader/blob/51da4f0c1952fc0564512be601fae369cbdd9380/terraform/azure/templates/cf_lb.tf#L88

When I deploy cf-deployment with the system domain `${var.system_domain}`, I can curl `api.${var.system_domain}` successfully.

A call to `api.${var.env_id}.${var.system_domain}` returns 404, so that the backend servers are considered as unhealthy.

```
404 Not Found: Requested route ('api.${var.env_id}.${var.system_domain} ') does not exist.
```

So, I think, the host should **NOT** include `${var.env_id}`. Could you please have a look?

**Comment by bingosummer** [comment]
CC: @genevieve

**Comment by genevieve** [comment]
Did you try `bbl up` with a terraform template that uses that as the host for the app gateway health probe? When we do it, this does not return a 404 and the backend servers are considered healthy. You can run `bbl plan --lb-type cf...` and modify the terraform template to point the probe at that host.

**Comment by bingosummer** [comment]
Here are my steps:
1. `bbl plan --lb-type cf --lb-cert ../app-gw-certs/PFX_FILE --lb-key ../app-gw-certs/PFX_FILE_PASSWORD`
1. Add `system_domain="foo.com"` to `vars/bbl.tfvars`
1. `bbl up`
1. Deploy cf-deployment with the system domain `foo.com`.
1. Then I can not login CF using `cf login -a https://api.foo.com --skip-ssl-validation`. And the status of the backend servers are unhealthy.
  ```
  $ cf login -a https://api.foo.com--skip-ssl-validation
  API endpoint: https://api.foo.com
  FAILED
  Server error, status code: 502, error code: 0, message:
  ```

  ![image](https://user-images.githubusercontent.com/4787647/37633067-e2bb633a-2c2b-11e8-8700-5e72e349453c.png)

**Comment by genevieve** [comment]
`bbl plan --lb-type cf --lb-cert ../app-gw-certs/PFX_FILE --lb-key ../app-gw-certs/PFX_FILE_PASSWORD --lb-domain foo.com`

**Comment by genevieve** [comment]
I believe you need to log in with `cf login -a https://api.bbl-env-erie...foo.com`

**Comment by bingosummer** [comment]
I agree that if I use `${var.env_id}.${var.system_domain}` as the system domain when I deploy cf-deployment (`bosh -d cf deploy cf-deployment.yml -o operations/azure.yml -o operations/scale-to-one-az.yml -v system_domain="${var.env_id}.${var.system_domain}" --vars-store=cf-deployment-vars.yml`) and log in with `cf login -a https://api.${var.env_id}.${var.system_domain}`, everything works.

But it's different from what I thought. My original thought is that `${var.system_domain}` is the system domain. And I don't understand why this env id is needed.

**Comment by genevieve** [comment]
We do it for uniqueness so that the user can provided the system domain that they have a zone for already, and we can create a zone that is scoped to a specific environment so they can continue to use that domain for more than one environment.

**Comment by genevieve** [comment]
I made the adjustment for azure, please let me know if you have any other trouble!
