### ISSUE TITLE
Errors when running `bbl plan` with `--lb-domain` on Azure

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-bootloader#281]
1. When running `bbl plan` with `--lb-domain`, I got the error:
    ```
    Error: resource 'azurerm_dns_a_record.bosh' config: unknown resource 'data.azurerm_public_ip.bosh' 
    referenced in variable data.azurerm_public_ip.bosh.ip_address
    ```

    A possible fix: https://github.com/bingosummer/bosh-bootloader/commit/5952bfd785064dff9d2c986e9452af4ed765c59a

2. Then I re-run `bbl plan`, there is a possibility of race condition.

    * When refreshing state of `data.azurerm_public_ip.cf-lb`, the creation of the public IP may be not finished.
         ```
         * data.azurerm_public_ip.cf-lb: data.azurerm_public_ip.cf-lb: Error making Read request on Azure public ip bbl-env-winnipeg-2018-03-18t16-08z-cf-lb-ip: network.PublicIPAddressesClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/publicIPAddresses/bbl-env-winnipeg-2018-03-18t16-08z-cf-lb-ip' under resource group 'bbl-env-winnipeg-2018-03-18t16-08z-bosh' was not found."
       ···

    * Even if the public IP is already created successfully when refreshing state of `data.azurerm_public_ip.cf-lb`, but the IP address of the public IP is not determined when creating the record for it.

    A possible fix: https://github.com/bingosummer/bosh-bootloader/commit/7fac8049e41e2f56624f6ad90173f9e19ce15485

**Comment by genevieve** [comment]
@bingosummer Did you specify `bbl plan --lb-type cf --lb-cert PFX_FILE --lb-key PFX_PASSWORD --lb-domain your.domain.com`?

**Comment by genevieve** [comment]
This has been fixed and will be in the next release!

**Comment by bingosummer** [comment]
@genevieve Thanks for your quick response.
It seems that only the first issue is fixed. Could you please check the second one?

**Comment by bingosummer** [comment]
Fixed in https://github.com/cloudfoundry/bosh-bootloader/commit/c52074cc5286db71d863d9c3cc561ffec8ed1f94
