### ISSUE TITLE
BBL cloud-config yaml for deployment on AWS with Bosh 2.0 and cf-deployment

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/bosh-bootloader#285]
Hi,

I am deploying CF using BBL, BOSH 2.0 and cf-deployment on AWS.
Following all steps from
https://docs.cloudfoundry.org/deploying/cf-deployment/index.html

Using bbl 6.4.7 (linux/amd64)

Doing a BBL up using 
bbl up \
    --iaas aws \
    --aws-access-key-id YOUR-ACCESS-KEY-ID \
    --aws-secret-access-key YOUR-SECRET-ACCESS-KEY \
    --aws-region YOUR-AWS-REGION \
    --lb-type cf \
    --lb-cert YOUR-CERT.crt \
    --lb-key YOUR-KEY.key \
    --lb-domain YOUR-SYSTEM-DOMAIN

1) After Deploying Bosh
$bbl print-env shows the output correctly, able to login to bosh using bosh log-in
AWS console shows the jumpbox/0, bosh/0 and bbl nat instance as running

2) This creates cloud-config.yml and ops.yml and after uploading the stemcell, we try to deploy CF using
bosh -e cloudconfig-env -d cf deploy cf-deployment/cf-deployment.yml --vars-store vars/cloud-config-vars.yml -v system_domain=test.com

This works partially OK and creates the CF components on AWS with vm_type as m4.large (as that is the default in ops.yml) Some instances are not created as we run out of AWS quota for m4.large

3) We wanted to change the m4.large to another value during the deployment to manage quota on AWS and have changed the ops.yml file for the same. Change vm_type minimal and vm_type small to other values

4) repeated the steps for bosh deploy but it doesnt pick up the updated ops.yml. We tried bosh update cloud-config cloud-config.yml. But this messes up the bosh deploy as the cloud-config.yml generated by bbl is still the template and doesnt have the aws specific replacements from ops.yml

5) If we try to change the instance type from AWS EC2 console and restart, the VMs go into unresponsive state

Can you please suggest what options we have to update the vm_type for instances when doing a bosh-deploy?

Thanks,

**Comment by genevieve** [comment]
In order to change the cloud-config uploaded to the director with bbl, you want to provide your own ops-file in `bbl-state-dir/cloud-config/your-ops-file.yml`. Then you can run `bbl up`. 

At the end of bbl up, bbl will run `bosh update-cloud-config cloud-config/cloud-config.yml -o cloud-config/ops.yml -o cloud-config/your-ops-file.yml`

**Comment by apsraps** [comment]
Thanks. I was able to get it to work by changing the ops.yml and executing the bosh update-cloud-config. Also had to give --vars-store= cloud-config-vars.yml in the update-cloud-config. Else it could not execute bosh deploy without the placeholders getting replaced (ideally it should not have happened but it did)

With the default cf-deployment file, the end of bosh deploy gave the AWS error - unable to create instances due to quota limits. Again, the quotas were within limits and no other instances were running on our aws instance. Had to deploy CF as in a non HA with all component instances as 1.
