### ISSUE TITLE
Feature request: flag to allow bbl print-env to talk to bosh director on local address. 

### ISSUE THREAD

**Issue by joshzarrabi** [cloudfoundry/bosh-bootloader#289]
Our concourse pipelines do a lot of bosh and credhub operations, and we authenticate by running `eval "$(bbl print-env)"` at the top of the task scripts. This works fine, however because the concourse is behind the same firewall as the bosh director, it would be really nice to be able to easily talk to it on 10.0.0.6 instead of going through the front door. 

So I am proposing adding a `--no-ssh` flag to `bbl print-env`, so if you are behind the firewall you can run `eval "$(bbl print-env --no-ssh)"`, and bbl would set the bosh director address as 10.0.0.6 and not set a socks5 proxy.

**Comment by evanfarrar** [comment]
Hey Josh,

I think this is a common enough configuration, but perhaps we could use the absence of a jumpbox to signify that the director is routable to the BOSH cli instead of a flag? We made a GCP patch for this situation, we could look at translating it to vsphere: https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/byobastion-gcp

**Comment by joshzarrabi** [comment]
@evanfarrar I'm a bit confused on how that would work. In our situation the jumbox does exist, we just don't want to talk to it in some situations.

**Comment by cppforlife** [comment]
i would also change `--no-ssh` to something else, since proxying to director api isnt really related to ssh-ing. may be `--no-proxy`.

**Comment by cwlbraa** [comment]
does `eval "$(bbl print-env)" && unset BOSH_ALL_PROXY CREDHUB_PROXY` not work?

**Comment by cwlbraa** [comment]
or even `eval "$(bbl print-env | grep -v PROXY)"`

**Comment by joshzarrabi** [comment]
After talking to @evanfarrar it sounds like @cwlbraa presented the best solution which is just to do it ourselves in bash. I will close this issue.
