### ISSUE TITLE
The acceptance test failed when using bbl on Azure

### ISSUE THREAD

**Issue by bingosummer** [cloudfoundry/bosh-bootloader#290]
We use bbl to deploy the application gateway, bosh director and cloud foundry.
Then we run the acceptance test. We hit an error. The application gateway can't transparently proxy the double quotes.
https://github.com/cloudfoundry/cf-acceptance-tests/issues/275.
@genevieve , did you see the failure case before?

**Comment by genevieve** [comment]
No, we have not seen that failure case.  We don't run the cf-acceptance-tests against a bbl'd up azure environment.

**Comment by genevieve** [comment]
I am going to close this issue since there aren't any changes to be made to the application gateway in the bbl azure terraform templates.
