### ISSUE TITLE
Upgrading from 5 with single ops file painful

### ISSUE THREAD

**Issue by anEXPer** [cloudfoundry/bosh-bootloader#291]
In v5, it was easy to make a small change to the director while letting bbl maintain most of the configuration. The --ops-file flag had some shortcomings, but it was super-usable for little things like flipping a feature switch or scaling the director's internal workers. Further, it was made even easier to use through `cf-deployment-concourse-tasks`, which worked around the one-ops-file limit by performing concatenation on our behalf.

When we moved from bbl5 to bbl6, we had a rough time of it. There were no clear instructions in either cf-dct or bbl about how to migrate from --ops-file/OPS_FILES to the new plan patch, though other parts of the migration were well explained. We couldn't figure out what deploy command file to base our override on, and ended up basing it on the one we had in our bbl-state (generated by v5), which was, of course, missing several variable declarations. We think we've fixed it, but we can't tell if our override is complete. We don't know how close we are to the official/base deploy command, or how we could tell if it changed.

I initially wanted to write this is as a feature request for the ability to just append a couple of things to the deploy command, so we didn't have to track its full state. That might be one solution, but the actual pain is that we weren't able to easily migrate what to us is a very simple feature: make it easy to adjust a particular bosh setting.

Another feature request might be to explicitly document the "base" plan-patch very clearly, document how to use it as a starting point, and make it part of your version. If you extend it at all, that's a breaking change, to the extent that everyone who has to maintain a copy needs to go manually update that copy.

**Comment by evanfarrar** [comment]
What would you think of us extending BOSH to 
```
bosh create-env -ops-files-directory $BBL_STATE_DIR/director-ops-files/ 
```

In this way, we wouldn't be adding "business logic" on top of bosh, and your could add an ops file in one step, without needing to modify create-director.sh file.

**Comment by anEXPer** [comment]
Hmm. It's also rough that you can't tell what actually happened via concourse output anymore. Did it use our ops file? Who knows!

**Comment by evanfarrar** [comment]
RE:
> Hmm. It's also rough that you can't tell what actually happened via concourse output anymore. Did it use our ops file? Who knows!
I have a mockup in my back pocket for that:
```
bbl has written the following files:
├── bbl-ops-files
│   └── gcp
│       └── bosh-director-ephemeral-ip-ops.yml
├── bbl-state.json
├── bosh-deployment
├── cloud-config
│   ├── cloud-config.yml
│   └── ops.yml
├── create-director.sh
├── create-jumpbox.sh
├── delete-director.sh
├── delete-jumpbox.sh
├── jumpbox-deployment
├── terraform
│   └── bbl-template.tf
└── vars
    └── bbl.tfvars

bbl found the following existing files:
├── terraform
    └── my-cool-override.tf
```

Would this give you more/enough insight into what bbl is doing?

**Comment by anEXPer** [comment]
Yeah, the approximate need here is something like "oh cool, it went green, did it use my thing? `command f my-ops-file` oh yeah there it is, sweet.

**Comment by joshzarrabi** [comment]
@anEXPer I definitely understand your pain and as a team we are trying to take measures to ease the pain of upgrading. We implemented @evanfarrar's idea in the following story: https://www.pivotaltracker.com/story/show/156143607, and we have talked about improving upgrade path testing when we have more bandwidth as a team.
