### ISSUE TITLE
allow configuration of vsphere vm folders

### ISSUE THREAD

**Issue by patrickhuber** [cloudfoundry/bosh-bootloader#292]
Currently bbl vsphere provider generates folders with the network name instead of allowing the user to specify folders. 

https://github.com/cloudfoundry/bosh-bootloader/blob/master/terraform/vsphere/template_generator.go

As a user I would like the ability to configure the vm, template and disk folders similar to how I can configure it in BOSH. 

ex: https://bosh.io/docs/init-vsphere.html

```
vcenter_templates: bosh-templates
vcenter_vms: bosh-vms
vcenter_disks: bosh-disks
```

**Comment by patrickhuber** [comment]
It appears I can work around this issue with the override scripts

**Comment by rowanjacobs** [comment]
I've just pushed a change that should allow you to customize the folder names by adding a custom `*.tfvars` file to the `vars` directory, with the `vcenter_disks_folder`, `vcenter_templates_folder`, and `vcenter_vms_folder` set to your preferred values. However, it may take some time for that to get through the pipeline into a release.

In the interim, another option would be to use the following plan patch:
```
.
├── terraform
│   └── vsphere-folders_override.tf
└── vars
    └── vsphere-folders.tfvars
```

where `vars/vsphere-folders.tfvars` looks like the vars file I described earlier and `terraform/vsphere-folders_override.tf` looks like:
```
output "vcenter_disks"     { value = "${var.vcenter_disks}" }
output "vcenter_templates" { value = "${var.vcenter_templates}" }
output "vcenter_vms"       { value = "${var.vcenter_vms}" }

variable "vcenter_disks"     {}
variable "vcenter_templates" {}
variable "vcenter_vms"       {}
```

**Comment by patrickhuber** [comment]
@rowanjacobs I noticed this change was brought into the current version of bbl, thanks for delivering that.

Testing this out, the terraform.tfstate indeed contains vcenter_disks, vcenter_templates and vcenter_vms variables and outputs. I tried to add a `lab.tfvars` with the following values:

```
vcenter_vms="bbl_lab_vms"
vcenter_disks="bbl_lab_disks"
vcenter_templates="bbl_lab_templates"
```

And the resultant `terraform.tfstate` file still contains the default values:

```
"vcenter_disks": {
  "sensitive": false,
  "type": "string",
  "value": "VM Network"
},
...
"vcenter_templates": {
   "sensitive": false,
   "type": "string",
   "value": "VM Network_templates"
},
"vcenter_vms": {
    "sensitive": false,
    "type": "string",
    "value": "VM Network_vms"
}
```

I can still create a provider override for these as a work around, but it looks like the values aren't passed through in the input generator terraform/vsphere/input_generator.go .

**Comment by rowanjacobs** [comment]
Can you try again with `vars/lab.tfvars` having the following entries?

```
vcenter_vms_folder="bbl_lab_vms"
vcenter_disks_folder="bbl_lab_disks"
vcenter_templates_folder="bbl_lab_templates"
```

**Comment by patrickhuber** [comment]
I'll give it a try. I ended up creating a pull request to get the folders through the bbl up and plan commands https://github.com/cloudfoundry/bosh-bootloader/pull/322

**Comment by joshzarrabi** [comment]
The p-r has been merged. Thank you!
