### ISSUE TITLE
Invalid firewall rule name when creating bosh-lite director

### ISSUE THREAD

**Issue by albertoleal** [cloudfoundry/bosh-bootloader#300]
Hi, 

I'm trying to create a bosh-lite director following [this README](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/getting-started-gcp.md) and I'm getting the following error:

```
Error: Error applying plan:

1 error(s) occurred:

* google_compute_firewall.bosh-director-lite-tcp-routing: 1 error(s) occurred:

* google_compute_firewall.bosh-director-lite-tcp-routing: Error creating firewall: googleapi: Error 400: Invalid value for field 'resource.name': 'bbl-env-great-salt-2018-04-28t07-48z-bosh-director-lite-tcp-routing'. Must be a match of regex '(?:[a-z](?:[-a-z0-9]{0,61}[a-z0-9])?)', invalid
```

Any tips on how to workaround this?

Thanks,

**Comment by rowanjacobs** [comment]
Can you try using a shorter environment name? There are currently some issues where the terraform templates in bbl may generate resource names that are too long, if the environment name is too long.

**Comment by albertoleal** [comment]
Hi @rowanjacobs , I didn't choose that name. I believe it's generated automatically [here](https://github.com/cloudfoundry/bosh-bootloader/blob/d920512d84166d0e6d7aacf82e8053bb1bdc54c1/helpers/env_id_generator.go#L64)

I manually changed the env.id to be 'env_id="bbl-env-**dog**-2018-04-28t07-48z"
' instead of 'env_id="bbl-env-**great-salt**-2018-04-28t07-48z"
' and it worked.

**Comment by cwlbraa** [comment]
@albertoleal this is definitely still a bug in the bosh-lite plan-patch. we should be using short env ids for this one.
