### ISSUE TITLE
destroying and re-creating lbs

### ISSUE THREAD

**Issue by apsraps** [cloudfoundry/bosh-bootloader#307]
Hi,

We are running CF on AWS for development and would like to keep a control on the costs incurred. We are able to bring down the EC2 instances for Bosh VMS using the bosh CLI.
We tried bbl plan and bbl up to destroy only the load balancers. However, we could not recreate the load balancers successfully along with the Security groups and then restart our bosh instances.

What is the correct way to recreate the load balancers and get it to work with existing bosh setup once we start the instances?

Thanks,

**Comment by evanfarrar** [comment]
@apsraps what you describe should have worked. Did you get some sort of terraform error during `bbl up`? Or did the load balancers create "fine" but you are not seeing traffic routing?
