### ISSUE TITLE
Using bbl from Google Cloud Shell

### ISSUE THREAD

**Issue by rkoster** [cloudfoundry/bosh-bootloader#313]
To get bbl to work from Google Cloud Shell we had to change the agent port of the jumpbox. Because of [this](https://cloud.google.com/shell/docs/limitations#outgoing_connections) limitation.
Would it be an option to switch to one of the allowed outgoing ports by default for the jumpbox on GCP? Or can we work with google to open the agent port (since they already have quite a random list of allowed ports).

```
cat > create-jumpbox-override.sh <<-EOF
#!/bin/sh
  bosh create-env \\
  \${BBL_STATE_DIR}/jumpbox-deployment/jumpbox.yml \\
  --state  \${BBL_STATE_DIR}/vars/jumpbox-state.json \\
  --vars-store  \${BBL_STATE_DIR}/vars/jumpbox-vars-store.yml \\
  --vars-file  \${BBL_STATE_DIR}/vars/jumpbox-vars-file.yml \\
  -o  \${BBL_STATE_DIR}/jumpbox-deployment/gcp/cpi.yml \\
  -o  \${BBL_STATE_DIR}/ops/google-shell-agent-port.yml \\
  --var-file  gcp_credentials_json="\${BBL_GCP_SERVICE_ACCOUNT_KEY_PATH}" \\
  -v  project_id="\${BBL_GCP_PROJECT_ID}" \\
  -v  zone="\${BBL_GCP_ZONE}"
EOF
chmod +x create-jumpbox-override.sh

mkdir -p ops
cat > ops/google-shell-agent-port.yml <<-EOF
- type: replace
  path: /cloud_provider/mbus
  value: https://mbus:((mbus_bootstrap_password))@((external_ip)):9600
- type: replace
  path: /cloud_provider/properties/agent/mbus
  value: https://mbus:((mbus_bootstrap_password))@((internal_ip)):9600
EOF

mkdir -p terraform
cat > terraform/google_shell_agent_port_override.tf <<-EOF
resource "google_compute_firewall" "external" {
  name    = "\${var.env_id}-external"
  network = "\${google_compute_network.bbl-network.name}"
  source_ranges = ["0.0.0.0/0"]
  allow {
    ports    = ["22", "9600", "25555"]
    protocol = "tcp"
  }
  target_tags = ["\${var.env_id}-bosh-open"]
}
EOF
```

**Comment by joshzarrabi** [comment]
Hi @rkoster You're welcome to submit a pull request with a plan patch that does this. It would essentially just be those two files you wrote in a `plan-patch` directory. 

I'm a bit curious about the use case and wonder how common this is? What is the motivation for using `bbl` from the google cloud shell?

**Comment by rkoster** [comment]
we use google cloud shell a lot for training, it allows us to fully control the environment and not have to spend time debugging workstation specific issues. Also running from cloud shell will speedup the deploy time since bosh create-env will be running from inside the gcp (which saves a lot of time on uploading releases to the created vm).
