### ISSUE TITLE
CFCR deploy on AWS fail while bosh deploy 

### ISSUE THREAD

**Issue by arghya88** [cloudfoundry/bosh-bootloader#317]
Step 6 of CFCR deployment in AWS fails with below error:

invalid argument for flag `-l, --vars-file' (expected []template.VarsFileArg): Deserializing variables file '/dev/fd/11': yaml: line 18: could not find expected ':'

**Comment by cwlbraa** [comment]
what do you have on line 18 of `bbl outputs`?

**Comment by arghya88** [comment]
@cwlbraa Worked when I tried with latest update
