### ISSUE TITLE
need to ssh in vms

### ISSUE THREAD

**Issue by wilfredwilly** [cloudfoundry/bosh-bootloader#318]
Hi All,

Good Day :)

Need to ssh to the following vms which is generated under cloudfoundry. Please help me out.

[root@ip-172-31-30-130 CFAR]# bosh vms
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 130. Done

Deployment 'cf'

Instance                                                  Process State  AZ  IPs         VM CID               VM Type        Active
adapter/cb008bdb-cf19-471f-8688-99c928de94b7              running        z1  10.0.16.6   i-0537eb9f0de65d315  minimal        -
api/74c8027c-4729-4a2e-8786-801a25939c00                  running        z1  10.0.16.11  i-0ce375080b82eb30d  small          -
cc-worker/a63df768-1ef9-47d4-b479-b2095a0352f2            running        z1  10.0.16.12  i-093ccdee58d3c956a  minimal        -
consul/23e55fc2-dcd1-4e5d-b8a3-4742e890b893               running        z1  10.0.16.4   i-0d46cfcde9eb03450  minimal        -
database/9de77f02-1f57-49a2-9950-42f6d0d83e83             running        z1  10.0.16.7   i-04c2cd8ad58e8063b  small          -
diego-api/c59f7244-12ce-4ead-883d-5c9a88fd09f5            running        z1  10.0.16.8   i-0974bbac7a784a8ee  small          -
diego-cell/4f6b5078-d738-4b94-8dc4-5f07c886d5b2           running        z1  10.0.16.17  i-03dbef26296b98965  small-highmem  -
doppler/108c1ffc-4472-471a-b46a-dc57089b6484              running        z1  10.0.16.16  i-0a9ae3b38b0d92f10  minimal        -
log-api/e72f9957-cde4-42f6-9974-c09d145d83c6              running        z1  10.0.16.18  i-0b101d2a214bc8c93  minimal        -
nats/f1375e84-5d53-4969-b4c6-5886c54e8fdb                 running        z1  10.0.16.5   i-0551086d8b251b0bd  minimal        -
router/17e04ef9-c3d4-46c9-946c-84a0426fe227               running        z1  10.0.16.13  i-0ea656471330c9dc6  minimal        -
scheduler/5ac974c9-c49f-4e69-8562-1f8c431da662            running        z1  10.0.16.15  i-03d7948061e4caa69  minimal        -
singleton-blobstore/c3347e76-f699-48e3-9bed-2c80b6a6198b  running        z1  10.0.16.10  i-0f40c0a0afc7c19e5  small          -
tcp-router/bcdf6246-b12d-44ab-b89e-2cef1bf92ee9           running        z1  10.0.16.14  i-005e9630ae23f7c94  minimal        -
uaa/15b0e948-897b-44bc-8acd-8139131dca1f                  running        z1  10.0.16.9   i-037e75c3cb3bb4109  minimal        -

15 vms

Succeeded
[root@ip-172-31-30-130 CFAR]#

**Comment by rowanjacobs** [comment]
Have you tried using the bosh ssh command? E.g., `bosh ssh router/0` to ssh onto the router VM.
