### ISSUE TITLE
SHA Mismatch when installing bbl via brew

### ISSUE THREAD

**Issue by jedi132000** [cloudfoundry/bosh-bootloader#319]
am getting a similar error when installing bbl.
i cant update if, i haven't installed bbl, hence brew upgrade bbl, did not work. Hope someone sees this

==> Installing bbl from cloudfoundry/tap
==> Downloading https://github.com/cloudfoundry/bosh-bootloader/releases/downloa
Already downloaded: /Users/oladimejioladipo/Library/Caches/Homebrew/bbl-v6.7.1.1_osx
Error: SHA256 mismatch
Expected: 65e3c9306f992bcc80132445db07d52dd6c461450b6008d4d2d18d6899604670
Actual: 827760734c9694ed8de676986f618f4924927101566fb076ab4345a7fe2a0209
Archive: /Users/oladimejioladipo/Library/Caches/Homebrew/bbl-v6.7.1.1_osx
To retry an incomplete download, remove the file above.

**Comment by mouellet** [comment]
I can confirm this.

@jedi132000, as a quick fix you can `brew edit bbl` and change the MacOS sha256 to the Actual value.

>

**Comment by jedi132000** [comment]
Seems to work now, i didnt have to run brew edit bbl. just did a new install
