### ISSUE TITLE
naming of director internal ip and jumpbox internal ip

### ISSUE THREAD

**Issue by patrickhuber** [cloudfoundry/bosh-bootloader#320]
I noticed when the outputs are generated from the `bbl up` command using vsphere for IaaS, the director internal ip and jumpbox internal ip outputs have extra underscores in the names:

actual

```
Outputs:

director__internal_ip = 192.168.2.6
director_name = bosh-lab
external_ip = 192.168.2.5
internal_cidr = 192.168.0.0/16
internal_gw = 192.168.1.1
jumpbox__internal_ip = 192.168.2.5
```

expected

```
Outputs:

director_internal_ip = 192.168.2.6
director_name = bosh-lab
external_ip = 192.168.2.5
internal_cidr = 192.168.0.0/16
internal_gw = 192.168.1.1
jumpbox_internal_ip = 192.168.2.5
```

not sure if this is a typeo, but it looks like the result of commits 9936af7387c2a9380591ddaa5bd88cbf838abd20 and 9936af7387c2a9380591ddaa5bd88cbf838abd20

**Comment by mouellet** [comment]
That's by design, See: https://github.com/cloudfoundry/bosh-bootloader/pull/236

**Comment by patrickhuber** [comment]
ok, my mistake. I thought it was a misconfiguration.
