### ISSUE TITLE
bbl up for vsphere fails for director behind proxy

### ISSUE THREAD

**Issue by ashishapy** [cloudfoundry/bosh-bootloader#331]
bbl up for vshpere fails when i run behind proxy. It creates jumpbox but fails while downloading releases for  bosh/director.

error as below:
`
Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-trusty-go_agent/3468.17'... Finished (00:00:37)

Started deploying
  Creating VM for instance 'jumpbox/0' from stemcell 'sc-2f84d865-73e6-4f8e-a82d-af8a0dd4618b'... Finished (00:00:20)
  Waiting for the agent on VM 'vm-1dc41c9c-2516-480d-bdb2-460ad0fc6ff6' to be ready... Finished (00:00:47)
  Rendering job templates... Finished (00:00:00)
  Updating instance 'jumpbox/0'... Finished (00:00:11)
  Waiting for instance 'jumpbox/0' to be running... Finished (00:00:00)
  Running the post-start scripts 'jumpbox/0'... Finished (00:00:01)
Finished deploying (00:01:25)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Succeeded
step: created jumpbox
step: creating bosh director
Deployment manifest: '/home/a603827/cfcr-bbl/bosh-deployment/bosh.yml'
Deployment state: '/home/a603827/cfcr-bbl/vars/bosh-state.json'

Started validating
  Downloading release 'bosh'... Failed (00:01:01)
Failed validating (00:01:07)

Failed to download from 'https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-266.2.0-ubuntu-trusty-3586.16-20180611-175207-293401672-20180611175210.tgz?versionId=SBu7LrRQFLuPNYoCGHQPO_3UlgYS5qc2':
  Unable to download:
    Performing GET request:
      Get https://s3.amazonaws.com/bosh-compiled-release-tarballs/bosh-266.2.0-ubuntu-trusty-3586.16-20180611-175207-293401672-20180611175210.tgz?versionId=SBu7LrRQFLuPNYoCGHQPO_3UlgYS5qc2: http: error connecting to proxy "enterprise-proxy-address": ssh: rejected: administratively prohibited (open failed)

Exit code 1

Create bosh director: Running /home/userid/cfcr-bbl/create-director.sh: exit status 1
`

**Comment by cxhercules** [comment]
Has this created a socks proxy and trying to tunnel via ssh? Can you share script or at least settings? @ashishapy 

BBL team has anyone had a chance to look at this? @evanfarrar @genevieve Thanks!

**Comment by haydonryan** [comment]
@cxhercules - This is not an option for most customers in government, finance, etc. As to create a tunnel would get flagged by security.  Many customers are behind a proxy - including the one I'm at at the moment.

**Comment by crdant** [comment]
I had this error just now, and it was caused because I wasn't allowing DNS egress to port 8.8.8.8 which is specified as the DNS for the jumpbox in the jumpbox deployment manifest. I adjusted the firewall (home lab, so I could) and `bbl up` continued apace.

**Comment by roy-prasenjit** [comment]
Any update on this error?
