### ISSUE TITLE
bbl should fail fast with helpful error message if bosh-init is too old

### ISSUE THREAD

**Issue by robdimsdale** [cloudfoundry/bosh-bootloader#34]
We ran into an issue where our bosh-init was too old. `bbl` should fail fast with clear error message stating the actual version, and the minimum version it requires

**Comment by Amit-PivotalLabs** [comment]
Hey @robdimsdale 

We prioritized this story but never actually followed up with a GitHub comment.  My bad.  We actually don't know what the required min is anymore, and no one else has reported this issue.  If this problem recurs, we'll reboot the story and try to capture minimum version requirements up front.  I'm closing this for now.
