### ISSUE TITLE
Helm does not work in CFCR deployed in AWS

### ISSUE THREAD

**Issue by arghya88** [cloudfoundry/bosh-bootloader#341]
Helm init happens successfully but when I do helm version it gives below error:

Client: &version.Version{SemVer:"v2.9.1", GitCommit:"20adb27c7c5868466912eebdf6664e7390ebe710", GitTreeState:"clean"}
Error: cannot connect to Tiller

Have checked that tiller deploy pods are running.

**Comment by cwlbraa** [comment]
I totally had this same problem when I tried to install helm, and never really figured out what was wrong with it! did you figure it out?

**Comment by joshzarrabi** [comment]
@cwlbraa Does helm need to have a smaller subnet or something?

**Comment by cwlbraa** [comment]
helm might be having a problem reaching itself (tiller) because tiller sometimes deploys into one of the subnets that the lbs (or api lb) can't reach
