### ISSUE TITLE
support for powershell export of `bbl print-env`

### ISSUE THREAD

**Issue by patrick-huber-pivotal** [cloudfoundry/bosh-bootloader#342]
Working with a customer who would like to have `bbl print-env` export powershell environment variables. I have done similar work here  https://github.com/patrickhuber/wrangle/tree/master/renderers and can work on a pull request to get this into bbl.

* The command should support both auto detection of shell ("windows"="powershell" otherwise="bash") 
* The user can specify the shell with a --shell powershell or --shell bash to override this default (ex: running powershell core on a mac)

**Comment by zachgersh** [comment]
hey @patrick-huber-pivotal - did you ever get to try this out? I am closing this as it has been accepted but feel free to reopen if you test it and it doesn't work.
