### ISSUE TITLE
Feature Request: Add support for `BBL_VSPHERE_DNS` and `BBL_VSPHERE_NTP`

### ISSUE THREAD

**Issue by eamonryan** [cloudfoundry/bosh-bootloader#344]
In vSphere environments, it is extremely common for users to utilise internal DNS and NTP servers. 

- Many environments do not even allow access to external ones
- Many are entirely disconnected from the internet
- Many just have addresses that are only resolvable internally and need their BOSH deployed VMs to be able to resolve them too

To support this, can we add a couple more global flags such as `BBL_VSPHERE_DNS` and `BBL_VSPHERE_NTP`?

I would expect that these values would then become the default DNS and NTP server for:
- The jumpbox
- The BOSH Director
- The initial networks generated for the cloud-config

**Comment by mcnichol** [comment]
Bumping this one. 

Feels like this would be an important addition.
