### ISSUE TITLE
concourse-bosh-deployment/cluster/operations/no-auth.yml doesn't exist

### ISSUE THREAD

**Issue by scottbri** [cloudfoundry/bosh-bootloader#346]
in the docs here: https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md
the option specifies no-auth.yml.

This file does not exist in the repo concourse/concourse-bosh-deployment

**Comment by rowanjacobs** [comment]
`no-auth.yml` was removed for concourse version 4.0.0. You can still use this ops file if you roll back to concourse-bosh-deployment [version 3.14.1](https://github.com/concourse/concourse-bosh-deployment/releases/tag/v3.14.1).

**Comment by joshzarrabi** [comment]
@scottbri Thanks for pointing this out, we will fix the docs.
