### ISSUE TITLE
bbl plan with azure should not check if the ressource group exist

### ISSUE THREAD

**Issue by fpeyre** [cloudfoundry/bosh-bootloader#350]
Good morning,

I use bbl-v6.9.0 on linux : 

My usecase:
I want make a bbl plan on azure to obtain some terraform files, and after apply the [plan](https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/byoresource-group-azure) patch to use an existing resource group on azure.

`./bbl --iaas azure  --name test --azure-subscription-id XXX --azure-tenant-id XXX --azure-client-id XXX --azure-client-secret XXX --azure-region eastus plan`

When I run this command, I obtain the following message:

`Env id manager sync: Check existence for resource group test-bosh: resources.GroupsClient#CheckExistence: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF`

But from what I understand, bbl plan should not talk to azure (see comment [`here`](https://github.com/cloudfoundry/bosh-bootloader/pull/326#issuecomment-411549238))

When I'm offline, I obtain the following message
`azure.BearerAuthorizer#WithAuthorization: Failed to refresh the Token for request to https://management.azure.com/subscriptions/XXX/providers/Microsoft.Storage/storageAccounts?api-version=2017-06-01: StatusCode=0 -- Original Error: adal: Failed to execute the refresh request. Error = 'Post https://login.microsoftonline.com/XXX/oauth2/token?api-version=1.0: dial tcp: lookup login.microsoftonline.com on 127.0.1.1:53: server misbehaving'`

It is a normal behaviour ?
Do we have an option to make a `bbl plan` without checking if the resource group exist on azure ?

**Comment by cwlbraa** [comment]
This is an interesting "bug" of sorts. I didn't realize that the Env id manager would check for environment name collisions during `bbl plan`. It's an interesting feature, and perhaps we should only do that on `bbl up`... but anyways, I think the bug here is that azure/client.go:25 assumes that your resource group name is formulated from your environment Id. When plan patching as I suggested in the other thread, we probably didn't have any permissioning issues around reading that particular test-bosh resource group. Anyways, if we instead used the terraform output resource_group_name to do this existence check, the behavior would be more predictable.

**Comment by titilambert** [comment]
@cwlbraa So can we submit a patch for that ?
If so could you give us more hint about where the changes should be done ?
Thanks !

**Comment by cwlbraa** [comment]
I'm rotating off this team next week, and honestly I'm not entirely certain about the scope of the changes. The env id manager is a very specific little component that's intended to provide helpful fast-fail errors. In this case, it's trying to make sure that you're not using a duplicated environment name. We might be able to make that behavior more predictable and plan-patch-aware, but I think it'd be a large change for a small gain. 

Looking back to the top of this issue, the thing we didn't address is that it looks like your azure account doesn't have sufficient permissions to check for the existence of the ${envID}-bosh resource group. If you could provide bbl with an azure key that's sufficiently privileged to verify that no such resource group exists, you should be able to move forward.
