### ISSUE TITLE
c4s no longer the latest instance type

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#357]
c5s are actually the latest (and even they came out in 2017). There should be an automated way to update the base cloud-config instance types.

**Comment by cdutra** [comment]
@zachgersh Thank you for filing this issue. Latest bbl uses bosh 266 and aws cpi 71 which yet doesn't have complete support for c5/m5 instance types for xenial stemcells.
The latest bosh-deployment has the necessary changes (aws cpi 72+ and bosh 267+) therefore we should bump them in the next release.

Thank you again!
