### ISSUE TITLE
concourse deployment

### ISSUE THREAD

**Issue by phopper-pivotal** [cloudfoundry/bosh-bootloader#360]
using https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md

the directions say to use;
<username>
<super-secret-password>

but don't indicate where these values should come from.

getting this error;

Task 10 | 21:10:54 | Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'web'. Errors are:
    - Unable to render templates for job 'atc'. Errors are:
      - Failed to find variable '/bosh-bbl-env-athabasca-2018-08-21t20-21z/concourse/atc_tls' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'
      - Failed to find variable '/bosh-bbl-env-athabasca-2018-08-21t20-21z/concourse/atc_tls' from config server: HTTP Code '404', Error: 'The request could not be completed because the credential does not exist or you do not have sufficient authorization.'

**Comment by joshzarrabi** [comment]
@phopper-pivotal I see, If you want to be able to talk over trusted tls you will need to pass in a cert/private_key pair that your workstation will recognize, otherwise you can pass the `tls_vars` operations file. I will update the docs. Thank you!
