### ISSUE TITLE
Unmarshalling service account key (must be valid json): invalid character '/' looking for beginning of value

### ISSUE THREAD

**Issue by gerhard** [cloudfoundry/bosh-bootloader#369]
I've upgraded bbl from v6.9.16 to v6.10.0 on macOS v10.13.6 and started getting this error:

```
Unmarshalling service account key (must be valid json): invalid character '/' looking for beginning of value
gmake: *** [/Users/gerhard/github.com/rabbitmq/sme/gcp/mk/cf.mk:49: /Users/gerhard/github.com/rabbitmq/sme/gcp/create-director.sh] Error 1
```

Service account key is valid json. Everything works fine with bbl v6.9.16

**Comment by cdutra** [comment]
@gerhard I tried to fresh `bbl up` with `v6.10.0` and it works for me. Are you upgrading from `v6.9.16` to `v6.10.0`? Could you provide the steps to reproduce? Thanks!

**Comment by cdutra** [comment]
@gerhard Are you setting the environment variable or passing a flag? Also, are you passing the file path or the key itself?

**Comment by gerhard** [comment]
The mistake is mine.

I was using:

```
bbl-v6.10.0_osx plan \
--gcp-service-account-key /Users/gerhard/github.com/rabbitmq/sme/gcp//Users/gerhard/github.com/rabbitmq/sme/gcp/rabbitmq-bosh-bbl.key.json ...
```

While I should have been using:

```
bbl-v6.10.0_osx plan \
--gcp-service-account-key /Users/gerhard/github.com/rabbitmq/sme/gcp/rabbitmq-bosh-bbl.key.json ...
```

All working as expected now, thank you!

**Comment by cdutra** [comment]
@gerhard Happy to hear it's working! Thanks for letting us know, we appreciate.
cc @crhntr
