### ISSUE TITLE
bbl down fails with isolation segment on GCP

### ISSUE THREAD

**Issue by MasslessParticle** [cloudfoundry/bosh-bootloader#373]
When we create envirionments with the iso-seg-gcp plan-patch, the create goes fine but `bbl plan/down` fails with a bunch of missing variables. 

I've tried to copy the iso-seg-gcp directory to the env directory with no luck

context: https://cloudfoundry.slack.com/archives/C2DBC3YGZ/p1536341446000100

**Comment by joshzarrabi** [comment]
You have to run `bbl plan` with `--lb-type cf`, `lb-cert`, `lb-key`, and `lb-domain`. `bbl` sets up different terraform if you supply these flags (ie it sets up a load balancer for you if you run `--lb-type cf`), and the terraform in the plan patch assumes that this terraform has been applied.
