### ISSUE TITLE
Azure AGW and ssh to apps container

### ISSUE THREAD

**Issue by jkujovic** [cloudfoundry/bosh-bootloader#377]
Hi all,

if I deploy CF with  bbl lf to azure, then cf use as lb azure application gateway. when I try cf shh  app-name.domainname ... to cf app  (ssh for apps and spaces is enabled), then  dns  app-name.domainname  return public address, which is public address  Azure app gw, (L7 - dealing only web traffic (Http, https and websocket, -no ssh) to cf router). so after period i get response 
 FAILED
Error opening SSH connection: dial tcp public_IP_appGW :2222: connect: connection timed out

how to configure azure for functional ssl to app container? I know one possibility is use Azure LB instead of Azur app GW, but for the web traffic i would like use App GW.

Thx for any idea

Jan

**Comment by joshzarrabi** [comment]
Hi @jkujovic, it looks like our terraform does not support diego ssh for azure right now, as application gateways do not support ssh. Thanks for bringing this to our attention. We will add a story to add this support, but for now you can write a plan patch to create a regular load balancer that directs ssh traffic on `2222` to your diego vm. Here is the terraform for the [forwarding rule] (https://github.com/cloudfoundry/bosh-bootloader/blob/master/terraform/gcp/templates/cf_lb.tf#L148-L155) and [target pool](https://github.com/cloudfoundry/bosh-bootloader/blob/master/terraform/gcp/templates/cf_lb.tf#L142-L146) on gcp. Please let us know if you need help.

cc @ciriarte @nmahoney-pivotal

**Comment by arjun024** [comment]
Hi! It would be really great to use bbl to get a bosh env on Azure suitable for a full CF without having to modify terraform templates. If there are plans to add this feature, please let us know.
