### ISSUE TITLE
bbl up does not update the bblVersion parameter inside the bbl-state.json file

### ISSUE THREAD

**Issue by srm09** [cloudfoundry/bosh-bootloader#379]
GIVEN: There is a bbl'd up GCP director with an earlier `bbl` version
WHEN: we update the director using `bbl --state-dir=<bbl-state-dir> up` command with a new bbl version binary
THEN: the `bblVersion` parameter inside the `bbl-state.json` file does not get updated with the updated version number

Is this expected functionality, is there any other way to update the director created using `bbl`?

**Comment by evanfarrar** [comment]
Hello @srm09, to upgrade your director, you have to explicitly opt into the new manifest and terraform that come embedded with the new BBL binary:
```
bbl plan # this writes a new manifest to your state directory
bbl up # this runs create-env with the new manifest
```

**Comment by zankich** [comment]
@evanfarrar so are you saying that running `bbl up` against a existing bbl'd director, with a new version of `bbl`, no longer upgrades your bosh director?

**Comment by evanfarrar** [comment]
Yes, `bbl up` will only re-apply your current plan, `bbl plan` will write a new plan to disk.
