### ISSUE TITLE
The doc to deploy Concourse is confusing

### ISSUE THREAD

**Issue by brightzheng100** [cloudfoundry/bosh-bootloader#386]
I was thinking [deploying Concourse](https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md) is one of the next follow-up steps for deploying Concourse cluster on top of BBL foundation. 
But actually it's NOT.

By following the step mentioned above, it would actually create a new set of infra, jumpbox, BOSH etc.

So why not make it very clear that this doc is for only deploying Concourse on top of existing BBL resources (again, the infra, jumpbox, BOSH etc.)?

**Comment by joshzarrabi** [comment]
I merged your pr, thank you!
