### ISSUE TITLE
No director__external_ip in bbl outputs

### ISSUE THREAD

**Issue by mrodriguezio** [cloudfoundry/bosh-bootloader#394]
Hi,

I've deployed bosh (bosh-lite) version in AWS, by following the patches setup for bosh lite.

However, I noticed that there's no `director__external_ip` in the `bbl outputs`. I've also inspected the terraform `plan-patches/bosh-lite-aws/terraform/bosh-lite_override.tf` file looking for that output variable. It exists for gcp (htts://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/bosh-lite-gcp/terraform/bosh-lite_override.tf#L47-L49), but it doesn't for aws.

The error arose while I was setting up the dns for cloud foundry deployment. cf-deployment repository is expecting that output variable: https://github.com/cloudfoundry/cf-deployment/tree/master/iaas-support/bosh-lite#2-set-up-dns

**Comment by zachgersh** [comment]
@mrodriguezio - we'd gladly take a PR to fix this and sorry about the delay in answering. We don't normally make too many guarantees about how well plan patches will work or the compatibility between them. I am closing for now, feel free to reopen if you'd like to discuss more!
