### ISSUE TITLE
Unable to spin a jumpbox and other using bbl up. screenshot attached. Someone please assist.

### ISSUE THREAD

**Issue by navin205** [cloudfoundry/bosh-bootloader#397]
Installing CPI:
  Compiling job package dependencies for installation:
    Compiling job package dependencies:
      Compiling package:
        Running command: 'bash -x packaging', stdout: 'Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Installing ansi 1.5.0
Installing ast 2.3.0
Installing little-plugger 1.1.4
Installing multi_json 1.12.1
Installing logging 1.8.2
Installing semi_semantic 1.2.0
Installing bosh_common 1.3262.24.0
Installing httpclient 2.8.3
Installing membrane 1.1.0
Installing bosh_cpi 2.4.1
Installing builder 3.2.3
Using bundler 1.16.0
Installing mini_portile2 2.1.0
Installing mono_logger 1.1.0
Installing nokogiri 1.7.2 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2/ext/nokogiri
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/bin/ruby
-r ./siteconf20181102-19742-1f7s0hr.rb extconf.rb --use-system-libraries
checking if the C compiler accepts ... yes
Building nokogiri using system libraries.
WARNING: libxml2 version 2.9.3 or later is highly recommended, but proceeding
anyway.
checking for xmlParseDoc() in libxml/parser.h... yes
checking for xsltParseStylesheetDoc() in libxslt/xslt.h... yes
checking for exsltFuncRegister() in libexslt/exslt.h... yes
checking for xmlHasFeature()... yes
checking for xmlFirstElementChild()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetParserStructuredErrors()... yes
checking for xmlRelaxNGSetValidStructuredErrors()... yes
checking for xmlSchemaSetValidStructuredErrors()... yes
checking for xmlSchemaSetParserStructuredErrors()... yes
creating Makefile

current directory:
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2/ext/nokogiri
make "DESTDIR=" clean

current directory:
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2/ext/nokogiri
make "DESTDIR="
compiling html_document.c
In file included from ./html_document.h:4,
                 from html_document.c:1:
./nokogiri.h:39:1: warning: "MAYBE_UNUSED" redefined
In file included from
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/include/ruby-2.4.0/ruby/ruby.h:24,
from
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/include/ruby-2.4.0/ruby.h:33,
                 from ./nokogiri.h:33,
                 from ./html_document.h:4,
                 from html_document.c:1:
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/include/ruby-2.4.0/x86_64-linux/ruby/config.h:133:1:
warning: this is the location of the previous definition
html_document.c: In function 'new':
html_document.c:16: error: #pragma GCC diagnostic not allowed inside functions
html_document.c:16: error: #pragma GCC diagnostic not allowed inside functions
html_document.c:16: warning: conversion to 'int' from 'long unsigned int' may
alter its value
html_document.c:16: error: #pragma GCC diagnostic not allowed inside functions
make: *** [html_document.o] Error 1

make failed, exit code 2

Gem files will remain installed in
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.7.2
for inspection.
Results logged to
/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/nokogiri-1.7.2/gem_make.out

An error occurred while installing nokogiri (1.7.2), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.7.2'` succeeds before bundling.

In Gemfile:
  nokogiri
', stderr: '+ set -e
+ BOSH_PACKAGES_DIR=/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages
+ cp -a vsphere_cpi/Gemfile vsphere_cpi/Gemfile.lock vsphere_cpi/bin vsphere_cpi/lib vsphere_cpi/vendor /root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi
+ export BUNDLE_CACHE_PATH=vendor/package
+ BUNDLE_CACHE_PATH=vendor/package
+ export BUNDLE_WITHOUT=development:test
+ BUNDLE_WITHOUT=development:test
+ bundle_cmd=/root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/bin/bundle
+ cd /root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/vsphere_cpi
+ /root/.bosh/installations/d5cd01d4-f39d-4f05-43ad-05781d59839c/packages/ruby-2.4-r3/bin/bundle install --local --no-prune --deployment
':
          exit status 5

Exit code 1

Create jumpbox: Running /root/Downloads/create-jumpbox.sh: exit status 1

**Comment by cdutra** [comment]
Please, reopen if the issue isn't fixed after installing dependencies. Thanks!
