### ISSUE TITLE
Issue with tf-backend-aws plan patch

### ISSUE THREAD

**Issue by axelaris** [cloudfoundry/bosh-bootloader#399]
Hi guys,
sorry for creating an issue instead of PR, but I'm not a Go guy, so can't fix it myself.

The thing is I want to keep terraform state file on S3. For that, I’ve configured [tf-backend-aws](https://github.com/cloudfoundry/bosh-bootloader/tree/master/plan-patches/tf-backend-aws) plan patch. When I run `bbl plan` - I got an error: 
`Error configuring the backend "s3": No valid credential sources found for AWS Provider.`

However, all credentials have been set by environment variables like `BBL_AWS_ACCESS_KEY_ID` and `BBL_AWS_SECRET_ACCESS_KEY`

And all AWS provision (instances, networks, balancers etc.) is working well except that S3 backend stuff.

I found a quick workaround for this:
```
export AWS_ACCESS_KEY_ID=$BBL_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$BBL_AWS_SECRET_ACCESS_KEY
```
If I run it before `bbl plan` - all is working smoothly. But I believe it shouldn’t be a permanent solution though.
Looking forward to see a fix from you!

**Comment by zachgersh** [comment]
hey @axelaris - the readme notes you have to edit the template either programmatically or manually to get these values into there (if you look the template has no interpolation). Apologies for the delay in answering.
