### ISSUE TITLE
support log features

### ISSUE THREAD

**Issue by blue-bird1** [cloudfoundry/bosh-bootloader#401]
When I encounter some errors, I can't find the reason from the log. I want to add a log function to help with the use and debugging.(I am new, if you have already provided, please let me know. I did not find it in the document)

**Comment by grenzr** [comment]
Have you tried using `--debug` switch on `bbl plan` or `bbl up` commands? If its BOSH issues you're having, you can use `BOSH_LOG_LEVEL=<something>` as per https://bosh.io/docs/cli-global-flags/#logging in front of your bbl command .. or... a combination of both. eg. `BOSH_LOG_LEVEL=debug bbl up --debug` .. its very verbose, but I've used this to find all my errors so far.

**Comment by zachgersh** [comment]
@blue-bird1 - let us know if @grenzr's answer helped.
