### ISSUE TITLE
bosh/0 instance is publicly accessible from the internet

### ISSUE THREAD

**Issue by diogomatsubara** [cloudfoundry/bosh-bootloader#403]
By default, `bbl plan` on aws creates bbl-ops-files/aws/bosh-director-ephemeral-ip-ops.yml which sets up an IP address for the bosh/0 instance. That instance then becomes accessible through the internet when ideally the director machine would only be accessible through the jumpbox.

The workaround is to use a create-director-override.sh with the ops-file removed, like this: https://gist.github.com/diogomatsubara/977beee7ac8a892ead7aaee617e48845

That works in the sense that the bosh/0 vm is not assigned a public ip, but the subnet the vm is created on ($env-id-bosh-subnet) routes traffic through the internet gateway and if instances don't have a public IP, they can't route traffic through an IG.

Any advice on what would be the proper fix here? I'm experimenting with creating a new subnet for bosh/0 which I can route its traffic through the NAT gateway (in my environment I'm using the nat gateway plan patch) and then keep the jumpbox in its own subnet routing traffice through IG.

I'll report back here once I get my experiment working but I wonder if other have run into similar issues and how this could be fixed.

**Comment by diogomatsubara** [comment]
It looks like my idea to have a separate subnet for the jumpbox won't be so straightforward. Terraform generated output from bbl, outputs `subnet_id` and then passes that to bosh in vars/director-vars-file.yml and vars/jumpbox-vars-file.yml

I could use the create-director-override.sh and create-jumpbox-override.sh to use a customized vars file but then I have to maintain the state of that vars file somehow whenever the terraform state changes.

**Comment by joshzarrabi** [comment]
Hi @diogomatsubara, We fixed this yesterday! https://github.com/cloudfoundry/bosh-bootloader/commit/10fe5cfc7c447a2e46033fd54f75e29635674edb. Should be out in the next release. You can copy our change into a plan patch for now. We took the route of just locking down traffic with firewall rules (only allow traffic on 22 from the jumpbox), so we didn't have to create another NAT box for internet access on the director.

**Comment by diogomatsubara** [comment]
Thanks @joshzarrabi ! I really appreciate this!

**Comment by diogomatsubara** [comment]
Hi @joshzarrabi, I just used bbl 6.10.54 (darwin/amd64) to bring up a new deployment and the bosh/0 is still exposing port 22 to the world.

**Comment by cdutra** [comment]
The fix hasn’t been released yet. It will be released in the next minor bump.

Cristovao Dutra

**Comment by diogomatsubara** [comment]
Thanks @cdutra!
