### ISSUE TITLE
Remove Backwards Compatibility Testing from BBL 7.x to 5.x

### ISSUE THREAD

**Issue by crhntr** [cloudfoundry/bosh-bootloader#409]
We found that NoDirector property in bbl state was only kept in the code base for 6.x to maintain backwards compatibility with BBL 5.x states.

Now that we are working towards a breaking release (7.x) we can modify ["state query against a bbl 5.1.0 state file"](https://github.com/cloudfoundry/bosh-bootloader/blob/ebc76b7ed9daf3a19ccbb0feb44ae66676ebc7c8/acceptance-tests/no-iaas/state_query_test.go) acceptance test to ensure backwards compatibility with BBL 6.x states.

This issue was discovered while working on this other one: [#161992133](https://www.pivotaltracker.com/story/show/161992133)

cc: @cdutra

**Comment by evanfarrar** [comment]
Removing NoDirector is a good idea, we do not need to support the 5-6 upgrade path any more in the 7.0 line.
