### ISSUE TITLE
Move ops files from BBL into kubo-deployment

### ISSUE THREAD

**Issue by evanfarrar** [cloudfoundry/bosh-bootloader#413]
### Why
To make the BBL / kubo-deployment division of code and responsibilities more similar to the BBL / cf-deployment 

#### How it works on CFAR 
- `cf-deployment`: contains YAML that references a Bosh deployment manifest
- `bosh-bootloader/plan-patches/routing-iso-seg-aws`: contains YAML for the Bosh director manifest, cloud config, and terraform

#### How it works on CFCR
- `kubo-deployment`: contains YAML that references a Bosh deployment manifest
- `bosh-bootloader/plan-patches/routing-iso-seg-aws`: contains YAML for the Bosh director manifest, cloud config, terraform, and *YAML that references a Bosh deployment manifest*.

This is not fixable with a single sustained effort. Today, I would like to identify what are the *YAML that references a Bosh deployment manifest* and open PRs for each of them to kubo-deployment, stating that we intend to eventually remove them from our repo, once we find them available in their repo.

### Acceptance Criteria
If there are *YAML patches that reference kubo-deployment* in `bosh-bootloader/plan-patches`
Then I see that they are also in `kubo-deployment`

### Links
https://github.com/cloudfoundry/bosh-bootloader/blob/master/plan-patches/cfcr-aws/cfcr-ops.yml
https://github.com/cloudfoundry-incubator/kubo-deployment

**Comment by alex-slynko** [comment]
Stories in CFCR tracker:
For GCP https://www.pivotaltracker.com/story/show/162415890
For Azure https://www.pivotaltracker.com/story/show/162414190
