### ISSUE TITLE
BYO jumpbox support?

### ISSUE THREAD

**Issue by grenzr** [cloudfoundry/bosh-bootloader#415]
Hi everyone! I'm using bbl in a rather locked down Azure sub that doesn't allow me to use public ips, and I have to use a corporate VPN to access Azure via an ExpressRoute link. The VPN only allows port 22/80/443 interactions to IPs inside its network. 

The jumpbox create-env creates the machine ok, but refuses to connect to port 6868 when attempting to provision the machine (port blockage across VPN). At this stage I cannot use socks+ssh proxy.

So, I created my own temp bastion using some simple terraform, and used `sshuttle` to it which gives me an all-port access to machines inside that vnet, including bosh agent, credhub ports etc.

I don't really want 2 jump boxes, so I looked at trying to skip the bbl creation of one.
I tried this by stubbing `create-jumpbox-override.sh`, but the bbl code tries to set `BOSH_ALL_PROXY` for the follow-on deployment of BOSH and fails).

I wanted to propose that if BOSH_ALL_PROXY is set in the environment before `bbl up` is run, then it skips the jumpbox creation, and uses your own use of the variable as the proxy for the bosh deployment.

Any thoughts?

**Comment by grenzr** [comment]
Another option I have is to use bosh create-env (using my pre-established bastion sshuttle) to deploy a bootstrap Concourse and use the open access and faster internet in Azure to do the bbl deployment (and others) without any jumpbox/proxy worries. 

However, I would still prefer to only have 1 jumpbox, and at the moment it just feels easier from a scripting perspective to stick with my byo terraform one.

**Comment by grenzr** [comment]
Gone down the road of using a terraform deployed bastion with sshuttle to bootstrap me a Concourse. A pipeline then does the BBL and permanent Concourse/pipeline deployments, and then tears down the terraform bastion at end, leaving the bosh jumpbox still behind.
Future sshuttle connections will use the bosh deployed jumpbox instead. Bit of scripting involved there, but turned it on myself to delete my own temp bastion in the end.

Probably works better eh.. :) Sorry to have disturbed you. Closing.

**Comment by crhntr** [comment]
Thanks for exploring this! Let us know if your solution continues to work for you and if not, feel free to reopen or create another issue. @Polar-Beard and I like your proposed solution for having BBL check the BOSH_ALL_PROXY variable before creating the jumpbox. We will bring this up to the team to see if we think we should support this. Thanks again!

**Comment by grenzr** [comment]
I was just about to open a new ticket going back on what I said earlier because I think there is a valid use case for not having a bbl jumpbox. I tried it the other way but I am still left with 2 bastion machines

I use `bosh create-env` to create a Concourse Lite in Azure and let my pipeline take it from there for deploying bbl and CFCR.

Because Concourse sits local to my deployments I don't need a bbl jumpbox (I do however still need my terraform created bastion as I use it to `sshuttle` through to allow bosh create-env to deploy concourse and access necessary ports from my locked down corporate network, plus it doesn't try to connect on port 6868 (refused on corp network) to complete the deployment.

The BOSH_ALL_PROXY override way Is good because you can use it to swap out with a BYO jumpbox, but might also be worth considering the possibility that some people might not want or need a jumpbox for various reasons too. So perhaps for that a config property to disable it?

**Comment by zachgersh** [comment]
@grenzr - I think for now we are going to cover the 90% case here and leave the jumpbox creation as a default. I appreciate all the discussion and work but most users will want a jumpbox and we aren't currently interested in maintaining a non-jumpbox specific configuration. 

Really appreciate the discussion and the issue.
