### ISSUE TITLE
bosh_director.tf exposes extra external ports on jumpbox

### ISSUE THREAD

**Issue by ohlookadollar** [cloudfoundry/bosh-bootloader#417]
bosh-bootloader/terraform/gcp/templates/bosh_director.tf creates the `external` resource to allow traffic from any source to the jumpbox:
```
resource "google_compute_firewall" "external" {
  name    = "${var.env_id}-external"
  network = "${google_compute_network.bbl-network.name}"

  source_ranges = ["0.0.0.0/0"]

  allow {
    ports    = ["22", "6868", "25555"]
    protocol = "tcp"
  }

  target_tags = ["${var.env_id}-bosh-open"]
}
```

Port 22 is expected. Do ports 6868 and 25555 need to be externally reachable?

**Comment by Polar-Beard** [comment]
Hi @ohlookadollar, thanks for creating this issue. We have those ports open for use by [bosh-deployment](https://github.com/cloudfoundry/bosh-deployment). Per their documentation, `6868` is for the `Agent for bootstrapping` and `25555` is for the `Director API` . Here's the section from their README on Security Groups for reference: https://github.com/cloudfoundry/bosh-deployment#security-groups.
