### ISSUE TITLE
`--lb-type=cf` on AWS should no longer require `--lb-cert` and `lb-key`

### ISSUE THREAD

**Issue by nwmahoney** [cloudfoundry/bosh-bootloader#422]
BBL now uses Network Load Balancers on AWS. These do not terminate TLS (it should be terminated at the gorouter when deploying CF). BBL still validates that the user supplies `--lb-cert` and `--lb-key`, even though it doesn't use them. This should be fixed. Maybe it should even validate that they are *not* supplied.

[This was brought to my attention in Slack](https://cloudfoundry.slack.com/archives/C2DBC3YGZ/p1546882822022500)

**Comment by nmahoney-pivotal** [comment]
`--lb-chain` should also be removed. It should probably  be removed completely, since I think AWS was the only place it was used.
