### ISSUE TITLE
Feature Request: Rotating Director Certificates

### ISSUE THREAD

**Issue by christianang** [cloudfoundry/bosh-bootloader#424]
Hello Team,

We have run into our director certificates expiring a couple times now and it would be great if bbl could automatically do this so I don't have to worry about when my certificates will expire. Having the director certificates expire is not great because once they expire you can no longer communicate with the bosh director and the bosh director is also unable to communicate with the VMs it manages.

Once you are in this state there is also no way to rotate the certificates without downtime.

Ideally, bbl could do this in either up or a separate command that I can run in CI on a weekly or monthly basis to preemptively rotate my certificates so they never hit the certificates 1 year expiration.

**Comment by genevieve** [comment]
This would be wonderful if it did it preemptively, or, at minimum, there was a command to do it.

**Comment by crhntr** [comment]
I am planning on working on this tomorrow.
 
Here are some relevant docs:
- https://bosh.io/docs/nats-ca-rotation/
- https://bosh.io/docs/blobstore-ca-rotation/

<img src="https://bosh.io/docs/images/nats_rotation.png"/>

**Comment by crhntr** [comment]
### Acceptance Criteria

**Given** I have a deployed bosh director and a deployment.
**When** I run some `bbl` command from the bbl state dir.
**Then** the command will rotate the ca certificate/s.

**Comment by genevieve** [comment]
Looks good, Christopher!

**Comment by ablease** [comment]
Hey, 

Is this feature request currently prioritised? We have just been stung by this issue, our director certs just expired and it would be nice if there was a way we could rotate them. 

We think the only way for us to proceed at the moment its to delete the bosh director and the deployments it manages and start from scratch. 

Thanks, 

Alex + @AartiKriplani

**Comment by zachgersh** [comment]
@ablease - not currently prioritized though we are interested in implementing this. Seems like the credhub team may also be thinking about cert rotation though I do not know how this impacts the director.

**Comment by winnab** [comment]
We on Services Enablement have also recently had to deal with this by recreating the Director and starting from scratch. It would be wonderful to have this option in the future.

**Comment by anEXPer** [comment]
Director cert expiration is one of the main obstacles to maintaining a low-effort/maintenance-mode project that uses BBL for CI. It would be lovely if we could build something that allowed folks to easily automate the rotation of these certs.

**Comment by gondoi** [comment]
Is the current workaround for this to delete the director and recreate? If so, this is not a viable option for us. Is there another option like removing the certs from state, or director vars and letting them regenerate?

**Comment by anEXPer** [comment]
You can delete the existing certs from the director vars store used by `bbl`. They will then be re-generated upon deployment. It's been a little while since I've done this so I don't have more details off the top of my head, but I could dig into it a bit if that becomes necessary.

**Comment by gondoi** [comment]
@anEXPer I guess I do need some details on how you did this. I removed the certs from the store and I'm still getting an error... Even on `bb up`:

```
Deploying:
  Creating instance 'bosh/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.0.0.6:6868/agent: x509: certificate has expired or is not yet valid

Exit code 1
```

**Comment by gmrodgers** [comment]
This would be quite nice thing to have.  The Platform recovery team experienced 4 directors needing to be rotated all at once.

**Comment by davidjahn** [comment]
We recently failed to rotate the CA cert for our bbl-deployed director. We failed, then had to tear down all of our infrastructure and rebuild it.

Would be great if bbl natively rotated CA certs.... because I don't think destroying all current infrastructure is an option for many teams.

**Comment by poligraph** [comment]
deleting file `director-vars-store.yml` worked, but in fact you have to save `credhub_encryption_password` from it.

so my sucessfull steps to rotate certificates:

1. mv `director-vars-store.yml` `director-vars-store.yml-save` in `vars` folder
2. `bbl plan`
3. `bbl up` - it will fail with credhub job on bosh-director vm
4. copy old credhub_encryption_password from `director-vars-store.yml-save` and replace it to newly created `director-vars-store.yml` 
5. run `bbl up` again

I hope this workaround help you

**Comment by gerhard** [comment]
That worked on bbl v6.10.18, thanks @poligraph 👍

**Comment by mdelillo** [comment]
Worked for me, though I also had to move `jumpbox-vars-store.yml`. Thanks!
