### ISSUE TITLE
JUMPBOX_PRIVATE_KEY variable isn't used in print-env output

### ISSUE THREAD

**Issue by arthfl** [cloudfoundry/bosh-bootloader#425]
If you run `bbl print-env` you get something like this:
```bash
export JUMPBOX_PRIVATE_KEY=/tmp/bosh-jumpbox123/bosh_jumpbox_private.key
export BOSH_ALL_PROXY=ssh+socks5://jumpbox@10.0.0.1:22?private-key=/tmp/bosh-jumpbox123/bosh_jumpbox_private.key
export CREDHUB_PROXY=ssh+socks5://jumpbox@10.0.0.1:22?private-key=/tmp/bosh-jumpbox123/bosh_jumpbox_private.key
```

Why not just use $JUMPBOX_PRIVATE_KEY in the two exports below?

**Comment by crhntr** [comment]
Thanks 

Usually this command is used like `eval "$(bbl print-env)"`.  So either way works. I see how you may want to print this out into a file and then edit the `JUMPBOX_PRIVATE_KEY` in a file and then source that file.

We often do as much as possible in Go to reduce issues with Zsh, Bash, or ... edge cases.

If it would make your workflow better, a PR would be welcome. 

https://github.com/cloudfoundry/bosh-bootloader/blob/52d9b049473fb72a26645b1561769660e4c11826/commands/print_env.go#L140-L142

**Comment by arthfl** [comment]
Yeah, it works totally fine currently. It's just about not-so-beautyful information duplication ;-)

I'll try to provide a PR for that.

**Comment by zachgersh** [comment]
@arthfl - I am going to close this for now. If you'd like to take a crack at a PR please re-open and we'll be glad to take a look!
