### ISSUE TITLE
Add ability to pass variables to update-runtime-config ops files

### ISSUE THREAD

**Issue by grenzr** [cloudfoundry/bosh-bootloader#428]
Hi all, I have the need to add an ops file to be used with update-runtime-config, however the code at https://github.com/cloudfoundry/bosh-bootloader/blob/e30762b7fe60ffa68474878bd83847e8d91d6519/bosh/config_updater.go#L52 doesn't specify --env-vars=BBL (or similar) to allow ENV vars to be setup before executing `bbl up`

Example:

Runtime ops file:

```
- type: replace
  path: /releases/name=bosh-dns/version
  value: ((bosh_dns_version))

- type: replace
  path: /releases/name=bosh-dns/url
  value: ((compiled_bosh_dns_url))
```

variable passed in by `export BBL_bosh_dns_version=".."` and `export BBL_compiled_bosh_dns_url`

Should be pretty straightforward to add and use BBL as the convention, however I am aware you're already using `BBL_` variables to configure `bbl` itself, so might be better to pick something else .. but you get the idea.

**Comment by fejnartal** [comment]
Hello @grenzr

My team and I are some of the maintainers of this project.
We are closing the issue since we don't have the time to implement
this ourselves and a lot of time has passed since its was created.

We would be very happy to review and merge any PRs implementing this though.
