### ISSUE TITLE
bbl cleanup-leftovers should show output when there's nothing to delete.

### ISSUE THREAD

**Issue by tylerschultz** [cloudfoundry/bosh-bootloader#441]
I had a corrupt environment and ran `bbl cleanup-leftovers --debug --filter my-env --gcp...`. There was nothing to delete and the command exited silently, emitting no output. 

I wasn't sure it had done anything. It would be nice to some output showing activity is happening.

**Comment by genevieve** [comment]
Hey @tylerschultz. If yall are still using this command, you can file an issue on the library (that emits those logs) directly: github.com/genevieve/leftovers
