### ISSUE TITLE
"bbl up" on AWS fails with Terraform error creating NS record

### ISSUE THREAD

**Issue by pmarkham** [cloudfoundry/bosh-bootloader#445]
BBL version: `bbl 7.2.12 (linux/amd64)`

IAAS: AWS

Running:

```
bbl up --debug  --name cftest  --iaas aws  --aws-access-key-id "XXXXX"  --aws-secret-access-key "XXXXX"  --aws-region ap-southeast-2  --lb-type cf  --lb-cert cert.pem  --lb-key key.pem  --lb-domain cftest.example.com
```

Give the following Terraform error:

```
Error: Error applying plan:

1 error(s) occurred:

* aws_route53_record.dns: 1 error(s) occurred:

* aws_route53_record.dns: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='cftest.example.com.', type='NS'] but it already exists]
	status code: 400, request id: 75f7c0dd-3bae-11e9-8512-5d3cdc8d8454
```

Commenting out the following lines in `terraform/bbl-template.tf` fixes the issue:

```
resource "aws_route53_record" "dns" {
  count = "${var.parent_zone == "" ? 1 : 0}"

  zone_id = "${local.zone_id}"
  name    = "${var.system_domain}"
  type    = "NS"
  ttl     = 300

  records = ["${local.name_servers}"]
}
```

It looks like AWS creates the NS records when the zone is created. Terraform then tries to add its own NS records which AWS rejects.

**Comment by Polar-Beard** [comment]
Hi @pmarkham, we noticed this issue too and just pushed a fix 😅 : https://github.com/cloudfoundry/bosh-bootloader/commit/08ed356bad251ed52a493522e8588b716b96fa4a

The error is a result of our templates not pinning to 1.X major version of the Terraform AWS provider, and version 2.0.0 of the provider was just released, so the terraform templates automatically pulled it in. The fix will be in the next release (7.3).

**Comment by cortega-lh** [comment]
@Polar-Beard - The issue you are fixing with (https://github.com/cloudfoundry/bosh-bootloader/commit/08ed356bad251ed52a493522e8588b716b96fa4a) is the one related to the AWS NAT instances, the one reported by @pmarkham is related to the route53 configurations.

```
* aws_route53_record.dns: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='cftest.example.com.', type='NS'] but it already exists]
	status code: 400, request id: 75f7c0dd-3bae-11e9-8512-5d3cdc8d8454
```

**Comment by cortega-lh** [comment]
@Polar-Beard - I understand now what you said. That was the commit number tied to `v7.3.0`. I can confirm that both errors (the one with route53 and the one with the instances size) are now fixed.

**Comment by zachgersh** [comment]
This has now been fixed by this release: https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v7.3.0

**Comment by pmarkham** [comment]
I've tested 7.3.0 and can confirm it's working for me.
