### ISSUE TITLE
bbl doesn't work with vsphere 6.5 when network names which include slash (/) or %2F

### ISSUE THREAD

**Issue by madushan1000** [cloudfoundry/bosh-bootloader#446]
My network name includes a slash(/), so I converder it to the url encoding as instructed by the bosh documentation. 
When I start with something like
```
export BBL_IAAS=vsphere
export BBL_VSPHERE_VCENTER_USER=user
export BBL_VSPHERE_VCENTER_IP=vc.local
export BBL_VSPHERE_VCENTER_DC=my-dc
export BBL_VSPHERE_VCENTER_CLUSTER=my-cluster
export BBL_VSPHERE_VCENTER_RP=BOSH-RP
export BBL_VSPHERE_NETWORK='VLAN9-10.10.7.0%2F24'
export BBL_VSPHERE_VCENTER_DS=my-ds
export BBL_VSPHERE_SUBNET_CIDR=10.10.7.0/24
export BBL_VSPHERE_VCENTER_DISKS=bosh/disks
export BBL_VSPHERE_VCENTER_TEMPLATES=bosh/templates
export BBL_VSPHERE_VCENTER_VMS=bosh/vms
```
and run `bbl up`, it throws an error, 
```
step: terraform init
step: terraform apply
step: creating jumpbox
Deployment manifest: '/home/madushan/bosh-vmware-k8s/jumpbox-deployment/jumpbox.yml'
Deployment state: '/home/madushan/bosh-vmware-k8s/vars/jumpbox-state.json'

Started validating
  Downloading release 'os-conf'... Skipped [Found in local cache] (00:00:00)
  Validating release 'os-conf'... Finished (00:00:00)
  Downloading release 'bosh-vsphere-cpi'... Skipped [Found in local cache] (00:00:00)
  Validating release 'bosh-vsphere-cpi'... Finished (00:00:00)
  Validating cpi release... Finished (00:00:00)
  Validating deployment manifest... Finished (00:00:00)
  Downloading stemcell... Skipped [Found in local cache] (00:00:00)
  Validating stemcell... Finished (00:00:03)
Finished validating (00:00:03)

Started installing CPI
  Compiling package 'ruby-2.4-r4/0cdc60ed7fdb326e605479e9275346200af30a25'... Finished (00:00:00)
  Compiling package 'iso9660wrap/2e7db549be4f20243d9e3b835df265e1a23d0ebb'... Finished (00:00:00)
  Compiling package 'vsphere_cpi/7556c6c966f3efcd1660cf2dc010e6c28a58182d'... Finished (00:00:00)
  Installing packages... Finished (00:00:00)
  Rendering job templates... Finished (00:00:00)
  Installing job 'vsphere_cpi'... Finished (00:00:00)
Finished installing CPI (00:00:01)

Starting registry... Finished (00:00:00)
Uploading stemcell 'bosh-vsphere-esxi-ubuntu-xenial-go_agent/250.9'... Skipped [Stemcell already uploaded] (00:00:00)

Started deploying
  Creating VM for instance 'jumpbox/0' from stemcell 'sc-e044d3d1-9ee2-4c2e-ba8b-6049ece336f4'... Failed (00:00:09)
Failed deploying (00:00:09)

Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'jumpbox/0':
    Creating VM:
      Creating vm with stemcell cid 'sc-e044d3d1-9ee2-4c2e-ba8b-6049ece336f4':
        CPI 'create_vm' method responded with error: CmdError{"type":"Unknown","message":"Unable to find network 'VLAN9-10.160.7.0%!F(MISSING)24'. Verify that the portgroup exists.","ok_to_retry":false}
Exit code 1


Create jumpbox: Running /home/madushan/bosh-vmware-k8s/create-jumpbox.sh: exit status 1
```

I tried different variations of the network name (VLAN9-10.10.7.0/24 or VLAN9-10.10.7.0%2f24), And i even tried putting the network in a folder (bosh/VLAN9-10.10.7.0/24) nothing worked. 
By enabling debug logs and cpi http logs, I verified the client actually retrieves a list of networks with the network I'm trying to deploy, but it looks like the client side validation ignores that network. 
Request/response soap message logs looks like this. (I also verified this using postman)

```
= Request

POST https://vc.local/sdk/vimService

Date: 2019-03-01 11:12:52 -0500
Additional Request Headers:
SOAPAction: "urn:vim25/6.7"
Accept-Encoding: gzip, deflate
Content-Type: text/xml; charset=UTF-8
Request Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<soapenv:Body><RetrieveProperties xmlns="urn:vim25"><_this type="PropertyCollector">propertyCollector</_this><specSet><propSet><type>Network</type><all>false</all><pathSet>name</pathSet></propSet><objectSet><obj type="Network">network-130</obj><skip>false</skip></objectSet></specSet></RetrieveProperties></soapenv:Body>
</soapenv:Envelope>

= Response

Status: 200 OK
Response Headers:
Date: Fri, 1 Mar 2019 16:12:52 GMT
Cache-Control: no-cache
Connection: Keep-Alive
Content-Type: text/xml; charset=utf-8
Content-Length: 550
Response Body:
<?xml version="1.0" encoding="UTF-8"?>
<soapenv:Envelope xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
 xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"
 xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
<soapenv:Body>
<RetrievePropertiesResponse xmlns="urn:vim25"><returnval><obj type="Network">network-130</obj><propSet><name>name</name><val xsi:type="xsd:string">VLAN9-10.10.7.0/24</val></propSet></returnval></RetrievePropertiesResponse>
</soapenv:Body>
</soapenv:Envelope>
```

I traced the error to somewhere near this [line](https://github.com/cloudfoundry/bosh-vsphere-cpi-release/blob/master/src/vsphere_cpi/lib/cloud/vsphere/vcenter_client.rb#L213) in the vsphere cpi, but I lack the ruby knowledge to go further. 

I also noticed that weird `VLAN9-10.10.7.0%!F(MISSING)24` is some sort of a ruby template post processing buy. The actual error thrwon by the cpi includes `VLAN9-10.160.7.0%2F24`

Can somebody help me to get this working, I can't change the network name.

**Comment by kajov** [comment]
If you haven't resolved this, we had the same issue with bbl throwing an error. What we figured out anywhere a special character in this case % and / for you will mess up bosh reading script and stop reading rest of the environmental values or in general just drop that variable that contains a special character. It's better if you use only alphanumeric characters without any additional special characters

**Comment by gsexton** [comment]
@kajov I was looking into this and found that the issue is that the string is getting shoved through Printf:

https://stackoverflow.com/questions/24661862/url-escaping-producing-amissing-instead-of-3a

So the solution for the MISSING is to escape the %. E.G. %%2f.

It still doesn't work, but the %!F(MISSING) error goes away, and it can't find the network. I've been playing some with govc, and from what I can see, govc ls /Datacenter/networkNetwork%2fPart isn't working right. Here are some patterns I see:

$]govc ls /Datacenter/network
/Datacenter/Network/a.b.c/25  (Network)
/Datacenter/Network/a.b.c Subnet (Network)
...

$]govc ls /Datacenter/Network/a.b.c Subnet
/Datacenter/network/a.b.c Subnet (Network)

$]govc ls /Datacenter/network/a.b.c%2f25
(nothing)

$]govc ls /Datacenter/network/a.b.c%2F25
(nothing)

So it looks like in addition to BOSH's escape handling issue, there's some sort of error in VMWare as well.
