### ISSUE TITLE
Cannot connect to AWS NAT instance

### ISSUE THREAD

**Issue by cortega-lh** [cloudfoundry/bosh-bootloader#459]
I'm trying to connect via SSH to the NAT instance created for my CF installation on AWS. I'd expect to see it listed when I run the command `bosh vms`. I was under the impression that BBL would create a PEM key for connecting into this machine, but it seems that it didn't (or I'm unable to find it).

Does anyone have an idea of how I can ssh this instance?

**Comment by diogomatsubara** [comment]
If you're using version 7.6.0 the NAT instance has been replaced by a NAT gateway and those are not ssh'able. Even with the older versions of bbl, I'm think `bosh vms` would not show the nat instance there as that's not a bosh managed vm, it's created and managed by the bbl terraform deployment before the director and jumpbox are deployed. Hope this helps.
