### ISSUE TITLE
BBL 8.0.0 incompatible with cf-d/loggregator on AWS

### ISSUE THREAD

**Issue by paulcwarren** [cloudfoundry/bosh-bootloader#470]
Hi there,

We ran into this issue a few days back.  When using bbl `8.0.0` (that reverted the recent NLB changes) it looks like the 4443 port was not added back into the cf-router security group.

This results in the following error when running cf commands like `cf start`:
```
timeout connecting to log server, no log will be shown
```

Steps to reproduce:
1. Deploy cf-d using cf-d-c-t v8.16.0 onto AWS
2. Push an app

Expected results:
- should see logs from the app

Actual results:
- we saw the above error and no log output from the app

NB: this caused the loggregator smoke test to fail.

cc/ @DennisDenuto @julian-hj

**Comment by nmahoney-pivotal** [comment]
Hey @paulcwarren. You mentioned that this causes the loggregator smoke tests to fail. I'm surprised that it wasn't caught in CI then as I'm under the impression that those are enabled by default. Did you have to do anything special to see the loggregator smoke tests fail? Or did you just deploy `cf-deployment` and see that failure?

**Comment by DennisDenuto** [comment]
@nmahoney-pivotal it was reproducible by just deploying `cf-deployment` to see smoke-tests fail.

**Comment by nmahoney-pivotal** [comment]
@DennisDenuto I think I have this fixed, but I couldn't reproduce the problem... Did you need to do anything special to enable the right smoke tests? My `bosh deploy -d cf cf-deployment ...` succeeded using a bosh director deployed with a bbl that did not include this fix.

**Comment by julian-hj** [comment]
@nmahoney-pivotal I believe that smoke tests are just a bosh errand you can run after your deployment finishes.

try `bosh -d cf run-errand smoke-tests`

**Comment by nmahoney-pivotal** [comment]
Thanks @julian-hj. I'll try running them explicitly.

**Comment by nhsieh** [comment]
Added the 4443 port back in release [v8.2.0](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v8.2.0). Let us know if the issue comes back.
