### ISSUE TITLE
When will the bosh-deployment get bumped to latest?

### ISSUE THREAD

**Issue by pritesh-patel95** [cloudfoundry/bosh-bootloader#475]
The latest `bbl` vendors a `bosh-deployment` that is 124 days old.

The latest bosh-deployment includes some bug-fixes which we have been affected by. Any idea on when we can expect a new `bbl` release which includes the latest `bosh-deployment`?

**Comment by nmahoney-pivotal** [comment]
The [latest release of bbl](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v8.1.1) should have what you're looking for!
