### ISSUE TITLE
Jumpbox : "Waiting until instance is ready : connection refused on 6868"

### ISSUE THREAD

**Issue by f-guichard** [cloudfoundry/bosh-bootloader#476]
Hello !

Environment : 
  - bbl 8.1.1
  - Ubuntu Trusty 14.04.5 LTS
  - Openstack Queens (RDO)

Issue : 
```
Started deploying
  Creating VM for instance 'jumpbox/0' from stemcell '34716450-50be-4305-aeac-ed310fe42b5b'... Finished (00:00:41)
  Waiting for the agent on VM '99737b2c-aa69-43d6-ae0a-68fade48ae1c' to be ready... Failed (00:09:59)
Failed deploying (00:11:08)

Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
  Creating instance 'jumpbox/0':
    Waiting until instance is ready:
      Post https://mbus:<redacted>@10.10.10.9:6868/agent: dial tcp 10.10.10.9:6868: connect: connection refused

Exit code 1
```

After proper configurations following [Getting Started Openstack](https://github.com/cloudfoundry/bosh-bootloader/blob/v8.1.1/docs/getting-started-openstack.md), i hit the error above.

It seems like bosh-agent is unable to start properly, which might be related to errors with reading user-data and creating settings.json file.

Try to ssh jumpbox vm with private key generated by terraform also fails (ssh -i bosh_jumpbox_private.key jumpbox@10.10.10.9), which made me think public key wasn't correctly read/written from metadata service to jumbox filesystem. And because there are 2 differents methods for reading those datas with openstack cpi (with configdrive or http), i tend to think my problem could be related with that.

I'm new with bbl/openstack cpi, so it might also be a dumb question. Sorry if that's the case !

**Comment by genevieve** [comment]
Hi @f-guichard. Is this still an issue or were you able to resolve it?
