### ISSUE TITLE
Unmarshalling service account key (must be valid json): invalid character ' ' in string escape code

### ISSUE THREAD

**Issue by himakshi-aggarwal** [cloudfoundry/bosh-bootloader#478]
getting "Unmarshalling service account key (must be valid json): invalid character ' ' in string escape code" error while trying to do a bbl up.

bbl plan has executed successfully.

**Comment by genevieve** [comment]
Hi @himakshi-aggarwal. `bbl plan` does not verify IaaS credentials when writing files. Only when you run `bbl up` are credentials verified against the IaaS. Were you able to resolve the formatting issue in your GCP service account key file?
