### ISSUE TITLE
Received 404 on bosh deploy - failed to find azs variable 

### ISSUE THREAD

**Issue by robdickens** [cloudfoundry/bosh-bootloader#500]
I received a 404 error while following the concourse deployment guide to deploy to azure: https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/concourse.md

The error was:
` Error: - Failed to find variable '/[env-name]/concourse/azs' from config server: HTTP Code '404', Error: 'The request could not be completed b                                                ecause the credential does not exist or you do not have sufficient authorization.'`

I used the following deploy command:
` bosh deploy -d concourse concourse.yml 
    -l ../versions.yml 
    -l ../../vars/concourse-vars-file.yml 
    -o operations/basic-auth.yml 
    -o operations/privileged-http.yml 
    -o operations/privileged-https.yml 
    -o operations/tls.yml 
    -o operations/tls-vars.yml 
    -o operations/web-network-extension.yml 
    -o operations/scale.yml 
    -o operations/worker-ephemeral-disk.yml`

I fixed this by adding `-v azs=[z1]` to the deploy command, however I was wondering if I should be including an additional operations file to resolve this instead of adding the az to the deploy command?

Either way, the guide did not highlight I would need to set this, should this be in there?
Also, I found it very useful to use the following command `bosh int concourse.yml --var-errs
` in order to diagnose the error, however I had to search through the issues to find this, is it worth adding this command to the guide as a helpful debug tool should issues arise?

**Comment by to30** [comment]
Hi @robdickens,

Add an argument to the command.
-v azs=[z1]

**Comment by robdickens** [comment]
Hi @to30, as you can see from above - that is what I did and not the question I was asking.

> I fixed this by adding -v azs=[z1] to the deploy command, however I was wondering if I should be including an additional operations file to resolve this instead of adding the az to the deploy command?

**Comment by to30** [comment]
Hi @robdickens,

I think it is a variable and should be added to vars/concourse-vars-file.yml

**Comment by robdickens** [comment]
Hi @to30 ,

Thanks for the advise, if we come across the issue again I will try your suggestion, but as this ticket was over a year ago we have since moved on, so I will close this.
