### ISSUE TITLE
Can we make credentials come from cloud native environment variables?

### ISSUE THREAD

**Issue by RealOrko** [cloudfoundry/bosh-bootloader#503]
This is super good folks, thanks to everyone involved. 

This is a request for a slight tweak, can we hoist auth params to optionally be sourced from cloud native environment variables first and then get overridden with params for bbl?

So parameters like (AWS):

`--aws-access-key-id`
`--aws-secret-access-key`
`--aws-region`
`--iaas` 

Can be substituted by:

`AWS_ACCESS_KEY_ID`
`AWS_SECRET_ACCESS_KEY`
`AWS_DEFAULT_REGION`
`BBL_IAAS`

I would also love to know through further discussion what the other cloud vendors/vsphere looks like with native support and help out with a PR on this. 

Many thanks!

**Comment by Infra-Red** [comment]
Hi @RealOrko 

Environment variables are supported for the parameters you mentioned:
```
--aws-access-key-id env: $BBL_AWS_ACCESS_KEY_ID
--aws-secret-access-key env: $BBL_AWS_SECRET_ACCESS_KEY
--aws-region env: $BBL_AWS_REGION
--iaas env: $BBL_IAAS
```

**Comment by RealOrko** [comment]
Thanks!
