### ISSUE TITLE
Standard_GS2: SKU not available error

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/bosh-bootloader#516]
Standard_GS2 is unavailable in my Azure account for some reason. This may be a larger problem or it may just be my account. However, this problem took me a while to figure out. It would be really nice to be able to designate a fallback VM type. Failing that, and if this is indeed a larger issue and not just my account, then I think we should replace `Standard_GS2` with `Standard_E4_v3` (a similar highmem option). That replacement worked fine for me when I slotted it.

https://github.com/cloudfoundry/bosh-bootloader/blob/b9b92c7b41fca198b59d19e1848292838f7d9e9d/cloudconfig/azure/base_ops_template.go#L89

**Comment by mkocher** [comment]
Maybe @dsboulder has some advice for what instance type we should default to these days?

**Comment by jcamara-dsg** [comment]
I've had to grab the cloud-config using bosh cloud-config then change the smallhighmem one to a VM size that's available in my region. Tried to use a similar one with high memory.

**Comment by ctlong** [comment]
Likely resolved by #534
