### ISSUE TITLE
bbl up fails due to terraform v1.0 openstack plugin openpgp signature

### ISSUE THREAD

**Issue by mephmanx** [cloudfoundry/bosh-bootloader#520]
[root@kolla tmp]# runuser -l stack -c 'bbl up --debug'
step: terraform init

Initializing provider plugins...

Checking for available provider plugins on https://releases.hashicorp.com...
Error installing provider "openstack": openpgp: signature made by unknown entity.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occured.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
terraform.d/plugins/linux_amd64

Executor init: Run terraform init --upgrade: exit status 1
[root@kolla tmp]# terraform -v
Terraform v1.0.0
on linux_amd64

I believe something needs to be updated due to the key rotation on the hashicorp side.

**Comment by gbandres98** [comment]
Hi @mephmanx, can you confirm that using bbl v8.4.43 fixes this issue? Thanks

**Comment by mephmanx** [comment]
I install bbl using homebrew....am I able to specify that version?  I would think that installing this way would get latest...

runuser -l stack -c  '/tmp/homebrew.sh </dev/null'
runuser -l stack -c  'echo "eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)" >> /opt/stack/.bash_profile'
runuser -l stack -c  'eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)'
runuser -l stack -c  'brew install cloudfoundry/tap/bosh-cli'
runuser -l stack -c  'brew install bbl'

It looks like this process is installing v8.4.0 (linux/amd64) (from bbl version)

**Comment by gbandres98** [comment]
Closing this issue as the original problem has been solved, and the bbl version in homebrew has been updated to v8.4.43
