### ISSUE TITLE
BBL up Openstack deployment API plugin incompatibility issue

### ISSUE THREAD

**Issue by mephmanx** [cloudfoundry/bosh-bootloader#527]
Yesterday during a fresh deployment of Openstack wallaby and attempted deployment of BOSH using BBL up I received this error.  It appears that hashicorp changed a plugin api version somewhere that has not yet been accounted for.

provider.openstack: Incompatible API version with plugin. Plugin version: 5, Core version: 4

Could we pin the plugin version or update compatibility?

Here is the full output:

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
step: terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "openstack" (1.44.0)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
step: terraform apply

Error: Error asking for user input: 1 error occurred:
	* provider.openstack: Incompatible API version with plugin. Plugin version: 5, Core version: 4

**Comment by mephmanx** [comment]
This is still open but I performed additional engineering to get around it.

**Comment by kinjelom** [comment]
fix: https://github.com/cloudfoundry/bosh-bootloader/pull/531

**Comment by mephmanx** [comment]
I just noticed this now, thank you!  I will update my configuration to try the latest version of this.  Much appreciated!
