### ISSUE TITLE
bbl down not documented in `bbl -h`

### ISSUE THREAD

**Issue by peterhaochen47** [cloudfoundry/bosh-bootloader#542]
`bbl -h` does not display the `bbl down` command, though it does display `bbl destroy`. It would be helpful to have them both in the help manual, so users would understand the difference between them (is there a difference?).

If they are the same, are you trying to promote `destroy` as the more standard one, as it is the one that is documented in the help manual? If so, it might be confusing that your in-repo docs (in /docs) are referencing `bbl down` more.

Version info:
```
bbl -v
bbl 8.4.110 (darwin/amd64)
```

**Comment by beyhan** [comment]
`bbl down` was the initial naming we used which changed to `bbl destroy`. `down` is still available because of backwards compatibility but we prefer the `bbl destroy` that is why `down` isn't documented.

**Comment by peterhaochen47** [comment]
@beyhan Thanks, I see.
Then I would revise my feedback to be able the references to `bbl down` in this repo's docs, for example, this doc: https://github.com/cloudfoundry/bosh-bootloader/blob/5e4f954d88181dd992d490feebffd5573cad6d92/docs/cleaning-up.md
If `bbl destroy` is preferred, it'll be better if the docs reference it instead of `bbl down`.

**Comment by beyhan** [comment]
@peterhaochen47 do you want to create a pr to fix the docs?
