### ISSUE TITLE
Bump to the latest bosh-deployment

### ISSUE THREAD

**Issue by peterhaochen47** [cloudfoundry/bosh-bootloader#544]
Hello, 

Could you bump to the latest bosh-deployment, which should contain [this commit](https://github.com/cloudfoundry/bosh-deployment/commit/3f90a5df152f65c8ce7e0833193e702d38beb253) that bumps CPI bosh-google-cpi to [version 46.0.0](https://github.com/cloudfoundry/bosh-google-cpi-release/releases/tag/v46.0.0) which contains a fix to a compatibility issue with GCP?

**Comment by peterhaochen47** [comment]
Or is there a way to configure/override the bosh-deployment version deployed by bbl?

**Comment by ramonskie** [comment]
the only way i know. (as bosh-deployment) is always overriden on a bbl up
in your bbl dir you could do a 
`git clone https://github.com/cloudfoundry/bosh-deployment.git bosh-deployment-new`
and add a `create-director-override.yml` that uses the `bosh-deployment-new` resources

it would contain something for gcp for example
```
#!/bin/sh
bosh create-env \
  ${BBL_STATE_DIR}/bosh-deployment-new/bosh.yml \
  --state  ${BBL_STATE_DIR}/vars/bosh-state.json \
  --vars-store  ${BBL_STATE_DIR}/vars/director-vars-store.yml \
  --vars-file  ${BBL_STATE_DIR}/vars/director-vars-file.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment-new/gcp/cpi.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment-new/jumpbox-user.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment-new/uaa.yml \
  -o  ${BBL_STATE_DIR}/bosh-deployment-new/credhub.yml \
  -o  ${BBL_STATE_DIR}/bbl-ops-files/gcp/bosh-director-ephemeral-ip-ops.yml \
  --var-file  gcp_credentials_json="${BBL_GCP_SERVICE_ACCOUNT_KEY_PATH}" \
  -v  project_id="${BBL_GCP_PROJECT_ID}" \
  -v  zone="${BBL_GCP_ZONE}" 
```
i created an issue to have a use latest flag see #536

**Comment by rkoster** [comment]
bosh-deployment has been bumped in the latest release: https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v8.4.111
