### ISSUE TITLE
Please bump the golang.org/x/sys dependency

### ISSUE THREAD

**Issue by clausecker** [cloudfoundry/bosh-bootloader#553]
This project depends on a version of golang.org/x/sys too outdated to support recent platforms such as arm64 or riscv64 freebsd.  Please bump the dependency to enable a build.

**Comment by ramonskie** [comment]
we are currently in the process of upgrading/updating bbl where we also move from go 1.13 to 1.19

**Comment by beyhan** [comment]
@clausecker do you want to provide a pr for this?

**Comment by clausecker** [comment]
Sorry, I don't have the capacity to prepare pull requests right now.  The change should be as simple as running

    go get golang.org/x/sys@latest

**Comment by ramonskie** [comment]
`golang.org/x/sys` is now bumped to `0.7.0`
when we upgraded to ginkov2
see https://github.com/cloudfoundry/bosh-bootloader/commit/8a26bab8b968c69b2889417e8ffa4e74415b01a3#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6L58

**Comment by ramonskie** [comment]
created pr #585 for adding arm binaries
