### ISSUE TITLE
Azure app gateway standard tier is deprecated. 

### ISSUE THREAD

**Issue by nronix** [cloudfoundry/bosh-bootloader#595]
https://github.com/cloudfoundry/bosh-bootloader/blob/139141d8addd95ef381a29ef98b6ce2e9a78c437/terraform/azure/templates/cf_lb.tf#L80

it is replaced by Standard_v2 or WAF_v2

**Comment by rkoster** [comment]
Could you make a PR for this change?

**Comment by jgbae** [comment]
May i create PR for this?
