### ISSUE TITLE
Scale up compilation VMs

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/bosh-bootloader#618]
Recent changes to the pxc release require larger compilation VMs for vanilla CF-D to succeed in being deployed on BOSH deployments created by bbl. Context: https://github.com/cloudfoundry/pxc-release/issues/53.

We are doing this manually for CF-D CI deployments but the change should probably be pushed back up to bbl.

cc @cloudfoundry/wg-app-runtime-deployments

**Comment by dimivel** [comment]
Here is a PR to scale up compilation VMs to fix pxc-release issue:
 https://github.com/cloudfoundry/bosh-bootloader/pull/619
