### ISSUE TITLE
bbl director-ca-cert is a breaking change

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [cloudfoundry/bosh-bootloader#68]
If it's not too much maintenance burden, we should still have the old command `bosh-ca-cert` aliased to `director-ca-cert`, but prints a deprecation warning **to STDERR** telling users to start using the new `director-ca-cert` command.

/cc @dsabeti @apshirley

**Comment by zankich** [comment]
This has been fixed in https://github.com/cloudfoundry/bosh-bootloader/commit/20cb9ccf0350c1ebc8d54cc3cb304ee41bb7dc44

**Comment by zankich** [comment]
This has been fixed in bbl [1.2](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v1.2.0)
