### ISSUE TITLE
feature-request: user-provided DNS name for director, in CA cert

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-bootloader#70]
I went to the trouble of setting up a DNS name for my bbl-created bosh director.  then I tried to target it using the new bosh cli.  I saw this:

```
bosh-cli env --ca-cert=/tmp/ca.cert bosh.trucker.c2c.cf-app.com trucker
Fetching info:
  Performing request GET 'https://bosh.trucker.c2c.cf-app.com:25555/info':
    Performing GET request:
      Get https://username:password@bosh.trucker.c2c.cf-app.com:25555/info: x509: certificate is valid for 35.160.98.150, not bosh.trucker.c2c.cf-app.com

Exit code 1
```

I'd like to be able to put my dns name in the CA cert, so that bosh doesn't complain like this.  I think that means I need to give the name at the time that I run `bbl up`.  

Thoughts?

**Comment by ematpl** [comment]
I'd also like the ability to specify a DNS SAN in the BOSH director's TLS certificate when I run `bbl up` to deploy or to update the director.

**Comment by evanfarrar** [comment]
@rosenhouse @ematpl this is now the case, at least in GCP, that BBL creates a DNS entry if you supply the --domain flag to create-lbs.

**Comment by rosenhouse** [comment]
I think my request is slightly different.  I'm asking about a DNS name in the CA cert for the bosh director itself, not for the LB.

**Comment by evanfarrar** [comment]
OK I think I understand. I will investigate if this is something that can be done via ops-files to the bosh director.

**Comment by evanfarrar** [comment]
Now that bbl accepts ops files in bbl v3 this could be done with the `--ops-file` flag: `bbl up --ops-file <(echo -e "- type: replace\n  path: /releases/name=bosh/version\n  value: bosh.trucker.c2c.cf-app.com")`

We could also consider `--domain` for `up` and having that follow through to the concourse LB and the system domain for CF
