### ISSUE TITLE
Feature Request: Destroy Only the Director

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#72]
Can we please have a flag to destroy just the director and nothing else?

**Comment by zankich** [comment]
What is the use case for this feature? Is it that you do not want a director at all?

**Comment by zachgersh** [comment]
the case would be where I want to keep my infrastructure but roll my director. Keeping the underlying IAAS paving would be nice.

**Comment by zankich** [comment]
Is this so that you can rotate credentials for the director?

**Comment by evanfarrar** [comment]
@zachgersh can you speak to Adrian's question? Now that we are moving towards create-env and var-store, if your goal is mainly credential related then we may be able to meet it in other ways.

**Comment by zachgersh** [comment]
I'd actually be happy to just close this :D
