### ISSUE TITLE
feature request: get the ssh gateway address

### ISSUE THREAD

**Issue by rosenhouse** [cloudfoundry/bosh-bootloader#74]
`bbl director-address` returns as an HTTPS URL with protocol and port:

```
bbl director-address
https://35.160.98.150:25555
```

This address cannot be passed to the BOSH cli as a gateway address for bosh ssh.

I'd like a way to automatically fill in the gateway address, without doing
```bash
bbl director-address | cut -d '/' -f 3 | cut -d ':' -f1
35.160.98.150
```

**Comment by zankich** [comment]
This has been addressed in bbl [1.2](https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v1.2.0)
