### ISSUE TITLE
an empty state file gives a cryptic error message

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-bootloader#75]
If you have an empty state file, every bbl command, which consumes the state file, responds with the message `EOF`, with no explanation of what or why it failed.

bbl version: https://github.com/cloudfoundry/bosh-bootloader/commit/907a25391bec1b60c718bc6b6f35f4f17da93b69

```
○ → du -h bbl-state.json
  0B    bbl-state.json
○ → cat bbl-state.json
○ → bbl up --aws-access-key-id XXX --aws-secret-access-key YYYY --aws-region WWWW


EOF
```

**Comment by evanfarrar** [comment]
I'm going to close this for now, because in the intervening time I've never seen this happen naturally or heard reports of it happening.
