### ISSUE TITLE
Feature Request: Rotate IAM User Access Key

### ISSUE THREAD

**Issue by jfmyers9** [cloudfoundry/bosh-bootloader#76]
This is currently impossible to do with `bbl` unless you mess with the cloudformation stack manually. It would be awesome if `bbl` made this easier to achieve. I believe there is a way to add `Serial` field to the `AWS::IAM::AccessKey` resource to indicate when you wish to rotate credentials.

*Note* If you manually revoke the AccessKey bbl will continue to use the wrong value when deploying the bosh director.

**Comment by evanfarrar** [comment]
Hello James, we've migrated AWS to IAM profiles in 4.0. These are managed / rotated via Amazon now, so this is resolved.
