### ISSUE TITLE
Allow VPC and subnets to be defined during bbl deploy

### ISSUE THREAD

**Issue by bstevenson** [cloudfoundry/bosh-bootloader#78]
Currently defining the VPC and subnet address space is not a feature of bbl.  For our uses case we do vpc-to-vpc peering for apps that don't fit into a CF model or spun up with a broker, so even though bbl will create separate VPCs per deployment, we can't have overlapping subnets.

Follow-up to Slack (#bbl-user) chat:
https://cloudfoundry.slack.com/archives/bbl-users/p1479503234000334

>"What's the best way to pass in or define the networks used when running `bbl up` in AWS.  If I wanted to change the VPC  and subnets from `10.0.0.0/16` to `10.10.0.0/16`(or whatever), would I need to manually go tweak the cloudformation template https://github.com/cloudfoundry/bosh->bootloader/blob/develop/aws/cloudformation/templates/fixtures/cloudformation_with_cf_elb.json and/or modify a `bosh.yml` file? "

**Comment by rauizab** [comment]
This seems to work for us:
* Clone https://github.com/cloudfoundry/bosh-bootloader/
* cd bosh-bootloader
* find . -type f -name "*.go" -exec sed -i 's/10\.0\./10\.100\./g' {} +
* find . -type f -name "*.yml" -exec sed -i 's/10\.0\./10\.100\./g' {} +
* find . -type f -name "*json" -exec sed -i 's/10\.0\./10\.100\./g' {} +
* go run bbl/main.go up --aws-access-key-id {accessKey} --aws-secret-access-key {secret} --aws-region eu-central-1 --iaas aws

**Comment by jcfigueiredo** [comment]
Hi, any update on this? It's sort of crucial for corporate installs. 

Thank you,

**Comment by varun7447** [comment]
Is there an update on this? I am trying to see if i can run VPC in /20 instead of using the default /16.

**Comment by jcfigueiredo** [comment]
Not an update but this gets us closer to it:
https://github.com/cloudfoundry/bosh-bootloader/blob/master/docs/advanced.md#terraform

**Comment by evanfarrar** [comment]
That is the currently recommended way to reduce/adjust your CIDR to compensate for your other networks. Feel free to re-open if you feel there could be an easier way.
