### ISSUE TITLE
Feature request: allow Datadog configuration for BOSH health manager

### ISSUE THREAD

**Issue by ematpl** [cloudfoundry/bosh-bootloader#82]
It would be useful for a BOSH deployed with `bbl up` to be capable of having its health manager configured with Datadog credentials, so that BOSH can send its VM usage metrics to a particular Datadog account.

**Comment by evanfarrar** [comment]
@ematpl we are going to allow bosh ops-files soon, is this health manager -> data-dog connection a bosh manifest property? Because if so, it can be set via ops-files, if not, we'll have to find another way.

**Comment by ematpl** [comment]
@evanfarrar Yes, in fact, here's an example ops-file that adds the configuration to bosh-deployment: https://github.com/cloudfoundry/diego-release/blob/73568bb9a1ce518ff95dc86c690daeb927155e06/examples/aws/ops-files/bosh/datadog.yml.

**Comment by evanfarrar** [comment]
Hey @ematpl this is resolved by bbl v3, you can now run `bbl up -o datadog.yml`

**Comment by ematpl** [comment]
Thanks, @evanfarrar !
