### ISSUE TITLE
please rename service_account_key flag to service_account_key_path

### ISSUE THREAD

**Issue by zachgersh** [cloudfoundry/bosh-bootloader#86]
I had no idea this was a file and instead tried to drop it a string of my service account key.

**Comment by ljfranklin** [comment]
I'd rather see this flag take either a path or the contents for the JSON file. We would like to interpolate this key into our pipeline config but instead we need to store it in S3 or a git repo.

**Comment by evanfarrar** [comment]
> I'd rather see this flag take either a path or the contents for the JSON file. We would like to interpolate this key into our pipeline config but instead we need to store it in S3 or a git repo.

We did this suggestion instead of the two flags. bbl now accepts the string contents of the file or that file, so that previous users' pipelines still work and new users will be less surprised/annoyed by this.

https://github.com/cloudfoundry/bosh-bootloader/releases/tag/v3.0.2
