### ISSUE TITLE
bbl create-lbs on GCP leaks credentials

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-bootloader#88]
bbl by default will output the terraform output, which leaks keys during `create-lbs`.

```
bbl create-lbs --type=cf --cert=bbl-cert --key=bbl-key
step: generating terraform template
..........
google_compute_ssl_certificate.cf-cert: Creating...
  certificate: "" => "+++++++++++LEAKED CERTIFICATE+++++++++++"
  description: "" => "user provided ssl private key / ssl certificate pair"
  name:        "" => "ENVID"
  private_key: "" => "++++++++++LEAKED KEY+++++++++++"
  self_link:   "" => "<computed>"
..........

step: finished applying terraform template
```

It would be great if bbl would not spew out terraform debug output by default. This is normally just noise, and does not provide much information to the user. It is useful however if you're debugging a failed deploy. A good option might be adding a `--debug` flag to bbl which will print out all terraform output, and the normal behaviour would suppress all extraneous output.

As it currently exists, if you use bbl for GCP in a public CI, you will leak your ssl private key.

**Comment by evanfarrar** [comment]
@zankich this is fixed in 2.1.0, the mechanism is as you suggested, Terraform output is silenced by default but users can ascertain the reason for failures with --debug.
