### ISSUE TITLE
gcp-service-account-key flag doesn't expand ~ in paths

### ISSUE THREAD

**Issue by dprotaso** [cloudfoundry/bosh-bootloader#91]
On OS X this will fail ~/Downloads/service-account-key.json

**Comment by evanfarrar** [comment]
Hey @dprotaso I can get stuff like this to work:

```
bbl update-lbs --cert ../../square/certstrap/out/cf.evanfarrar.com --key ../../square/certstrap/out/cf.evanfarrar.com.key
```
And also see it working with ~ expansion. However, this doesn't work: 

```
bbl update-lbs --cert=../../square/certstrap/out/cf.evanfarrar.com --key=../../square/certstrap/out/cf.evanfarrar.com.key
```

The guilty party here is bash and not bbl. We could not expand ~ in this situation without replicating some of bash's own features. Similarly, GNU grep, which I consider a pretty robust and mature command line utility, understands this:
```
grep --file ~/pattern.txt ~/.bash_history
```

but not this
```
grep --file=~/pattern.txt ~/.bash_history
```

I'm going to close without fixing. In my example I've made an assumption about the exact way you are trying to provide the flag (with --flag-name=value), feel free to re-open with a counter-example if my assumption was incorrect.
