### ISSUE TITLE
it would be nice if bbl would pollute your environment with bosh env vars

### ISSUE THREAD

**Issue by zankich** [cloudfoundry/bosh-bootloader#95]
It would be nice if bbl would set the required env vars for use with the new bosh cli, `BOSH_CLIENT`, `BOSH_CLIENT_SECRET`, etc.

The container networking team has a [bash function](https://github.com/cf-container-networking/c2c-workspace/blob/9bfc5a44e3b468ecc284d20d6a12094a646c3631/shared.bash#L157-L193) which achieves the same thing,  but it would be nice if bbl provided a simple command such as `bbl set env` or something like that.

This is something that every team has to implement themselves whenever they want to use bbl. My team has to write scripts which effectively do the same exact thing.

@mcwumbly @cppforlife

**Comment by evanfarrar** [comment]
@zankich this is available in 2.4.1.

`eval $(bbl print-env)`

**Comment by christianang** [comment]
One small modification to the above because of a bash quirk. You will want to run `eval "$(bbl print-env)"`. Running without quotes, bash will turn new lines to spaces whereas with quotes will preserve newlines.
