### ISSUE TITLE
bbl create-lbs on GCP doesn't print Terraform error messages when given a bad cert

### ISSUE THREAD

**Issue by sunjayBhatia** [cloudfoundry/bosh-bootloader#96]
When creating a load balancer on GCP, if you provide a bad cert, the error message that bbl produces is not very helpful. Not sure if this is a problem for all terraform commands, but the terraform errors do not come up through bbl for `create-lbs` on GCP.

Repro:
- generate a rsa:4096 key and cert
- run `bbl create-lbs --type cf --key PATH_TO_KEY --cert PATH_TO_CERT`

When the key provided is not a rsa:2048 key or if no Content Name is provided when generating the csr/cert, we get the following error:
```
step: generating terraform template


exit status 1
```

It appears that the errors that are collected and outputted [here](https://github.com/cloudfoundry/bosh-bootloader/blob/master/commands/gcp_create_lbs.go#L93) are not actually being collected from terraform. We had to go into the temporary directory and run the terraform command manually to actually get the error output.

**Comment by evanfarrar** [comment]
Hello Sunjay,

In response to a previous request #88 we stopped printing the output of terraform to avoid printing the cert and key inadvertently.

This output can still be seen if bbl is run with a "--debug" global flag. Your issue does bring to light some things we could do to better document that flag, such as noting that it is an option in failure messages, without contravening that original request which was presented as a security blocker for some folks using bbl.

**Comment by sunjayBhatia** [comment]
Ah that makes sense, we should have used the `--debug` flag.

I agree with your statement about documenting the flag and if there was something that said something to the effect of `Run with --debug to get more output` when errors occur, that would be super helpful.

Thanks!
