### ISSUE TITLE
bbl should not require terraform and bosh-init installed to run bbl director-username (etc)

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry/bosh-bootloader#98]
When trying to extract the `director-username`, `director-password`, `director-ca-cert`, or `director-address`, `bbl` requires terraform and bosh-init and ruby to be installed.  Those requirements are cumbersome when using CI to target a bosh director, so it would be nice if they were not required at all for this basic credential extraction.

**Comment by jaresty** [comment]
cc: @ChunyiLyu

**Comment by evanfarrar** [comment]
Hello @jaresty we are in the process of not requiring bosh-init on any command: https://www.pivotaltracker.com/story/show/137733131

By using bosh instead. Given that you intend to use `director-username`, `director-password`, `director-ca-cert`, and `director-address` with the bosh cli, is it also a problem that the bosh cli will become required to run those commands?

**Comment by jaresty** [comment]
@evanfarrar We usually have the bosh-cli installed already in the CI containers where we would use bbl to extract those credentials, so I don't anticipate any issue with that requirement.
